// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.winnexo20260512.models;

import com.aliyun.tea.*;

public class RunSkillRequest extends TeaModel {
    /**
     * <p>The placeholder variable value that stores the error message for a fault.</p>
     * 
     * <strong>example:</strong>
     * <p>string_value</p>
     */
    @NameInMap("arguments")
    public java.util.Map<String, ?> arguments;

    /**
     * <p>The idempotency token generated by the caller. In the current version, this value is only recorded in metadata and is not used for deduplication.</p>
     * 
     * <strong>example:</strong>
     * <p>string_value</p>
     */
    @NameInMap("clientToken")
    public String clientToken;

    /**
     * <p>The abstract model name (model tier). Defaults to standard if not specified.</p>
     * 
     * <strong>example:</strong>
     * <p>quick</p>
     */
    @NameInMap("model")
    public String model;

    /**
     * <p>The digital worker name. Used to calculate the CodeAgent allowedSkills whitelist based on binding relationships.</p>
     * 
     * <strong>example:</strong>
     * <p>string_value</p>
     */
    @NameInMap("operatingObjectName")
    public String operatingObjectName;

    /**
     * <p>The skill code (globally unique). This parameter takes priority over skillName.</p>
     * 
     * <strong>example:</strong>
     * <p>string_value</p>
     */
    @NameInMap("skillCode")
    public String skillCode;

    /**
     * <p>The skill name. Used when skillCode is not specified. The name must be unique within the tenant scope.</p>
     * 
     * <strong>example:</strong>
     * <p>string_value</p>
     */
    @NameInMap("skillName")
    public String skillName;

    /**
     * <p>The tenant ID. This is a common parameter. If not specified, the default tenant of the caller is used.</p>
     * 
     * <strong>example:</strong>
     * <p>10000</p>
     */
    @NameInMap("tenantId")
    public String tenantId;

    public static RunSkillRequest build(java.util.Map<String, ?> map) throws Exception {
        RunSkillRequest self = new RunSkillRequest();
        return TeaModel.build(map, self);
    }

    public RunSkillRequest setArguments(java.util.Map<String, ?> arguments) {
        this.arguments = arguments;
        return this;
    }
    public java.util.Map<String, ?> getArguments() {
        return this.arguments;
    }

    public RunSkillRequest setClientToken(String clientToken) {
        this.clientToken = clientToken;
        return this;
    }
    public String getClientToken() {
        return this.clientToken;
    }

    public RunSkillRequest setModel(String model) {
        this.model = model;
        return this;
    }
    public String getModel() {
        return this.model;
    }

    public RunSkillRequest setOperatingObjectName(String operatingObjectName) {
        this.operatingObjectName = operatingObjectName;
        return this;
    }
    public String getOperatingObjectName() {
        return this.operatingObjectName;
    }

    public RunSkillRequest setSkillCode(String skillCode) {
        this.skillCode = skillCode;
        return this;
    }
    public String getSkillCode() {
        return this.skillCode;
    }

    public RunSkillRequest setSkillName(String skillName) {
        this.skillName = skillName;
        return this;
    }
    public String getSkillName() {
        return this.skillName;
    }

    public RunSkillRequest setTenantId(String tenantId) {
        this.tenantId = tenantId;
        return this;
    }
    public String getTenantId() {
        return this.tenantId;
    }

}
