// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.ecd20200930.models;

import com.aliyun.tea.*;

public class GetAsyncTaskResponseBody extends TeaModel {
    /**
     * <p>The execution result. A value of <code>success</code> indicates success. Otherwise, an error message is returned.</p>
     * 
     * <strong>example:</strong>
     * <p>success</p>
     */
    @NameInMap("Code")
    public String code;

    /**
     * <p>The data information.</p>
     */
    @NameInMap("Data")
    public GetAsyncTaskResponseBodyData data;

    /**
     * <p>The request ID.</p>
     * 
     * <strong>example:</strong>
     * <p>1CBAFFAB-B697-4049-A9B1-67E1FC5F****</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>Indicates whether the operation is successful.</p>
     * 
     * <strong>example:</strong>
     * <p>true</p>
     */
    @NameInMap("Success")
    public String success;

    public static GetAsyncTaskResponseBody build(java.util.Map<String, ?> map) throws Exception {
        GetAsyncTaskResponseBody self = new GetAsyncTaskResponseBody();
        return TeaModel.build(map, self);
    }

    public GetAsyncTaskResponseBody setCode(String code) {
        this.code = code;
        return this;
    }
    public String getCode() {
        return this.code;
    }

    public GetAsyncTaskResponseBody setData(GetAsyncTaskResponseBodyData data) {
        this.data = data;
        return this;
    }
    public GetAsyncTaskResponseBodyData getData() {
        return this.data;
    }

    public GetAsyncTaskResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public GetAsyncTaskResponseBody setSuccess(String success) {
        this.success = success;
        return this;
    }
    public String getSuccess() {
        return this.success;
    }

    public static class GetAsyncTaskResponseBodyData extends TeaModel {
        /**
         * <p>The asynchronous task ID.</p>
         * 
         * <strong>example:</strong>
         * <p>000e89fb-cf8f-11e9-8ab4-b6e98080****</p>
         */
        @NameInMap("AsyncTaskId")
        public String asyncTaskId;

        /**
         * <p>The total number of items that have been processed by the asynchronous task, such as the number of files that have been packaged for a server-side package download task.</p>
         * 
         * <strong>example:</strong>
         * <p>100</p>
         */
        @NameInMap("ConsumedProcess")
        public String consumedProcess;

        /**
         * <p>The error code of the asynchronous task.</p>
         * 
         * <strong>example:</strong>
         * <p>InternalError</p>
         */
        @NameInMap("ErrCode")
        public Long errCode;

        /**
         * <p>The error message of the asynchronous task.</p>
         * 
         * <strong>example:</strong>
         * <p>The request failed due to some unknown errors. Please try again later.</p>
         */
        @NameInMap("Message")
        public String message;

        /**
         * <p>The task status.</p>
         * 
         * <strong>example:</strong>
         * <p>Failed</p>
         */
        @NameInMap("Status")
        public String status;

        /**
         * <p>The total number of items to be processed by the asynchronous task, such as the number of files to be packaged for a server-side package download task.</p>
         * 
         * <strong>example:</strong>
         * <p>1000</p>
         */
        @NameInMap("TotalProcess")
        public Long totalProcess;

        /**
         * <p>The download URL of the data generated by the asynchronous task, such as the download URL generated by a server-side package download task.</p>
         * 
         * <strong>example:</strong>
         * <p><a href="https://data.aliyunpds.com/hz22%2F5d5b986facbec311ef844c25954f96821497b383%2F5d5b986f955410dd991646bb87c6b4e899eff525?Expires=xxx&OSSAccessKeyId=xxx&Signature=xxx">https://data.aliyunpds.com/hz22%2F5d5b986facbec311ef844c25954f96821497b383%2F5d5b986f955410dd991646bb87c6b4e899eff525?Expires=xxx&amp;OSSAccessKeyId=xxx&amp;Signature=xxx</a></p>
         */
        @NameInMap("Url")
        public String url;

        public static GetAsyncTaskResponseBodyData build(java.util.Map<String, ?> map) throws Exception {
            GetAsyncTaskResponseBodyData self = new GetAsyncTaskResponseBodyData();
            return TeaModel.build(map, self);
        }

        public GetAsyncTaskResponseBodyData setAsyncTaskId(String asyncTaskId) {
            this.asyncTaskId = asyncTaskId;
            return this;
        }
        public String getAsyncTaskId() {
            return this.asyncTaskId;
        }

        public GetAsyncTaskResponseBodyData setConsumedProcess(String consumedProcess) {
            this.consumedProcess = consumedProcess;
            return this;
        }
        public String getConsumedProcess() {
            return this.consumedProcess;
        }

        public GetAsyncTaskResponseBodyData setErrCode(Long errCode) {
            this.errCode = errCode;
            return this;
        }
        public Long getErrCode() {
            return this.errCode;
        }

        public GetAsyncTaskResponseBodyData setMessage(String message) {
            this.message = message;
            return this;
        }
        public String getMessage() {
            return this.message;
        }

        public GetAsyncTaskResponseBodyData setStatus(String status) {
            this.status = status;
            return this;
        }
        public String getStatus() {
            return this.status;
        }

        public GetAsyncTaskResponseBodyData setTotalProcess(Long totalProcess) {
            this.totalProcess = totalProcess;
            return this;
        }
        public Long getTotalProcess() {
            return this.totalProcess;
        }

        public GetAsyncTaskResponseBodyData setUrl(String url) {
            this.url = url;
            return this;
        }
        public String getUrl() {
            return this.url;
        }

    }

}
