// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.live20161101.models;

import com.aliyun.tea.*;

public class CreateRtcAsrTaskRequest extends TeaModel {
    /**
     * <p>The authentication key used to generate the MD5 signature for callback information.</p>
     * <blockquote>
     * <p>Two authentication fields are added to the request header during callback: &quot;SIG-TIME&quot; indicates the current timestamp, and &quot;ASR-SIG&quot; indicates the MD5 authentication field. The &quot;ASR-SIG&quot; field is generated by the rule md5(<code>${SIG-TIME}/${callbackurl}/${authKey}</code>).</p>
     * </blockquote>
     * 
     * <strong>example:</strong>
     * <p>abcd</p>
     */
    @NameInMap("AuthKey")
    public String authKey;

    /**
     * <p>The automatic stream disconnection delay, in seconds. Valid values: 1 to 10.</p>
     * 
     * <strong>example:</strong>
     * <p>5</p>
     */
    @NameInMap("AutoTerminateDelay")
    public Long autoTerminateDelay;

    /**
     * <p>Specifies whether to automatically close the task when the stream disconnection exceeds the maximum delay. Default value: false.</p>
     * 
     * <strong>example:</strong>
     * <p>true</p>
     */
    @NameInMap("AutoTerminateEnabled")
    public Boolean autoTerminateEnabled;

    /**
     * <p>The callback URL.</p>
     * <p>This parameter is required.</p>
     * 
     * <strong>example:</strong>
     * <p><a href="http://xxx.com">http://xxx.com</a></p>
     */
    @NameInMap("CallbackURL")
    public String callbackURL;

    /**
     * <p>The channel ID.</p>
     * <blockquote>
     * <p>This parameter is required when Mode is set to rtc. Otherwise, this parameter does not take effect.</p>
     * </blockquote>
     * 
     * <strong>example:</strong>
     * <p>channelId</p>
     */
    @NameInMap("ChannelID")
    public String channelID;

    /**
     * <p>The language of the source audio. Valid values:</p>
     * <ul>
     * <li>ja: Japanese.</li>
     * <li>yue: Cantonese.</li>
     * <li>fspk: Chinese-English free speech.</li>
     * <li>en: English.</li>
     * <li>cn: Chinese.</li>
     * </ul>
     * <p>This parameter is required.</p>
     * 
     * <strong>example:</strong>
     * <p>cn</p>
     */
    @NameInMap("Language")
    public String language;

    /**
     * <p>The stream mode. Valid values: live and rtc. The value live indicates a standard live stream such as RTMP.</p>
     * <p>This parameter is required.</p>
     * 
     * <strong>example:</strong>
     * <p>live</p>
     */
    @NameInMap("Mode")
    public String mode;

    @NameInMap("OwnerId")
    public Long ownerId;

    /**
     * <p>The region ID.</p>
     * 
     * <strong>example:</strong>
     * <p>cn-shanghai</p>
     */
    @NameInMap("RegionId")
    public String regionId;

    /**
     * <p>The callback reporting interval, in milliseconds. Valid values: -1 to 500.</p>
     * <ul>
     * <li>-1: Does not accept intermediate results. Only full-sentence callbacks are accepted.</li>
     * <li>0 or not set: Reports callback results in real time.</li>
     * <li>&lt;=500 milliseconds: Reports callback results at periodic intervals.</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>5</p>
     */
    @NameInMap("ReportInterval")
    public Long reportInterval;

    /**
     * <p>The stream ingest user ID.</p>
     * <blockquote>
     * <p>This parameter is required when Mode is set to rtc. Only one value can be specified. Otherwise, this parameter does not take effect.</p>
     * </blockquote>
     * 
     * <strong>example:</strong>
     * <p>user1</p>
     */
    @NameInMap("RtcUserId")
    public String rtcUserId;

    /**
     * <p>The ApsaraVideo Real-time Communication application ID.</p>
     * <blockquote>
     * <p>This parameter is required when Mode is set to rtc. Otherwise, this parameter does not take effect.</p>
     * </blockquote>
     * 
     * <strong>example:</strong>
     * <p>appId</p>
     */
    @NameInMap("SDKAppID")
    public String SDKAppID;

    /**
     * <p>The streaming URL.</p>
     * <blockquote>
     * <p>This parameter is required when Mode is set to live. Otherwise, this parameter does not take effect.</p>
     * </blockquote>
     * 
     * <strong>example:</strong>
     * <p>rtmp://xxx</p>
     */
    @NameInMap("StreamURL")
    public String streamURL;

    /**
     * <p>The target translation language. Valid values:</p>
     * <ul>
     * <li>cn: Chinese.</li>
     * <li>en: English.</li>
     * <li>ja: Japanese.</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>en</p>
     */
    @NameInMap("TargetLanguages")
    public String targetLanguages;

    /**
     * <p>Specifies whether to enable translation.</p>
     * 
     * <strong>example:</strong>
     * <p>true</p>
     */
    @NameInMap("TranslateEnabled")
    public Boolean translateEnabled;

    public static CreateRtcAsrTaskRequest build(java.util.Map<String, ?> map) throws Exception {
        CreateRtcAsrTaskRequest self = new CreateRtcAsrTaskRequest();
        return TeaModel.build(map, self);
    }

    public CreateRtcAsrTaskRequest setAuthKey(String authKey) {
        this.authKey = authKey;
        return this;
    }
    public String getAuthKey() {
        return this.authKey;
    }

    public CreateRtcAsrTaskRequest setAutoTerminateDelay(Long autoTerminateDelay) {
        this.autoTerminateDelay = autoTerminateDelay;
        return this;
    }
    public Long getAutoTerminateDelay() {
        return this.autoTerminateDelay;
    }

    public CreateRtcAsrTaskRequest setAutoTerminateEnabled(Boolean autoTerminateEnabled) {
        this.autoTerminateEnabled = autoTerminateEnabled;
        return this;
    }
    public Boolean getAutoTerminateEnabled() {
        return this.autoTerminateEnabled;
    }

    public CreateRtcAsrTaskRequest setCallbackURL(String callbackURL) {
        this.callbackURL = callbackURL;
        return this;
    }
    public String getCallbackURL() {
        return this.callbackURL;
    }

    public CreateRtcAsrTaskRequest setChannelID(String channelID) {
        this.channelID = channelID;
        return this;
    }
    public String getChannelID() {
        return this.channelID;
    }

    public CreateRtcAsrTaskRequest setLanguage(String language) {
        this.language = language;
        return this;
    }
    public String getLanguage() {
        return this.language;
    }

    public CreateRtcAsrTaskRequest setMode(String mode) {
        this.mode = mode;
        return this;
    }
    public String getMode() {
        return this.mode;
    }

    public CreateRtcAsrTaskRequest setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }
    public Long getOwnerId() {
        return this.ownerId;
    }

    public CreateRtcAsrTaskRequest setRegionId(String regionId) {
        this.regionId = regionId;
        return this;
    }
    public String getRegionId() {
        return this.regionId;
    }

    public CreateRtcAsrTaskRequest setReportInterval(Long reportInterval) {
        this.reportInterval = reportInterval;
        return this;
    }
    public Long getReportInterval() {
        return this.reportInterval;
    }

    public CreateRtcAsrTaskRequest setRtcUserId(String rtcUserId) {
        this.rtcUserId = rtcUserId;
        return this;
    }
    public String getRtcUserId() {
        return this.rtcUserId;
    }

    public CreateRtcAsrTaskRequest setSDKAppID(String SDKAppID) {
        this.SDKAppID = SDKAppID;
        return this;
    }
    public String getSDKAppID() {
        return this.SDKAppID;
    }

    public CreateRtcAsrTaskRequest setStreamURL(String streamURL) {
        this.streamURL = streamURL;
        return this;
    }
    public String getStreamURL() {
        return this.streamURL;
    }

    public CreateRtcAsrTaskRequest setTargetLanguages(String targetLanguages) {
        this.targetLanguages = targetLanguages;
        return this;
    }
    public String getTargetLanguages() {
        return this.targetLanguages;
    }

    public CreateRtcAsrTaskRequest setTranslateEnabled(Boolean translateEnabled) {
        this.translateEnabled = translateEnabled;
        return this;
    }
    public Boolean getTranslateEnabled() {
        return this.translateEnabled;
    }

}
