// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sophonsoar20250903.models;

import com.aliyun.tea.*;

public class GetPlaybookResponseBody extends TeaModel {
    /**
     * <p>Configuration information of the playbook.</p>
     */
    @NameInMap("Playbook")
    public GetPlaybookResponseBodyPlaybook playbook;

    /**
     * <p>The ID of this request, a unique identifier generated by Alibaba Cloud for the request, which can be used for troubleshooting and problem localization.</p>
     * 
     * <strong>example:</strong>
     * <p>BFEFB76D-DD0E-5529-BD57-0DAC10B9B30F</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    public static GetPlaybookResponseBody build(java.util.Map<String, ?> map) throws Exception {
        GetPlaybookResponseBody self = new GetPlaybookResponseBody();
        return TeaModel.build(map, self);
    }

    public GetPlaybookResponseBody setPlaybook(GetPlaybookResponseBodyPlaybook playbook) {
        this.playbook = playbook;
        return this;
    }
    public GetPlaybookResponseBodyPlaybook getPlaybook() {
        return this.playbook;
    }

    public GetPlaybookResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public static class GetPlaybookResponseBodyPlaybook extends TeaModel {
        /**
         * <p>Creation time (in milliseconds).</p>
         * 
         * <strong>example:</strong>
         * <p>1731378251000</p>
         */
        @NameInMap("CreateTime")
        public Long createTime;

        /**
         * <p>Description of the playbook.</p>
         * 
         * <strong>example:</strong>
         * <p>waf ip blocked</p>
         */
        @NameInMap("PlaybookDescription")
        public String playbookDescription;

        /**
         * <p>Extended information of the playbook.</p>
         * 
         * <strong>example:</strong>
         * <p>{&quot;opCode&quot;:1}</p>
         */
        @NameInMap("PlaybookExtension")
        public String playbookExtension;

        /**
         * <p>List of playbook input parameter configurations.</p>
         */
        @NameInMap("PlaybookInputConfigs")
        public java.util.List<FieldInputConfig> playbookInputConfigs;

        /**
         * <p>Name of the playbook, without special characters.</p>
         * 
         * <strong>example:</strong>
         * <p>waftest</p>
         */
        @NameInMap("PlaybookName")
        public String playbookName;

        /**
         * <p>List of playbook output parameter configurations.</p>
         */
        @NameInMap("PlaybookOutputConfigs")
        public java.util.List<FieldOutputConfig> playbookOutputConfigs;

        /**
         * <p>Parameter type of the playbook, with the following values:</p>
         * <ul>
         * <li><strong>template-ip</strong>: IP entity.</li>
         * <li><strong>template-file</strong>: File entity.</li>
         * <li><strong>template-process</strong>: Process entity.</li>
         * <li><strong>template-host</strong>: Host entity.</li>
         * <li><strong>template-domain</strong>: Domain entity.</li>
         * <li><strong>template-container</strong>: Container entity.</li>
         * <li><strong>template-incident</strong>: Security incident.</li>
         * <li><strong>template-alert</strong>: Security alert.</li>
         * <li><strong>custom</strong>: Custom.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>template-ip</p>
         */
        @NameInMap("PlaybookParamType")
        public String playbookParamType;

        /**
         * <p>Input example of the playbook.</p>
         * 
         * <strong>example:</strong>
         * <p>{&quot;ip&quot;:&quot;1.<em>.</em>.1&quot;}</p>
         */
        @NameInMap("PlaybookParamsExample")
        public String playbookParamsExample;

        /**
         * <p>Publication status of the playbook, with the following values:</p>
         * <ul>
         * <li><strong>0</strong>: Unpublished.</li>
         * <li><strong>1</strong>: Published.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("PlaybookStatus")
        public Integer playbookStatus;

        /**
         * <p>Workflow of the playbook.</p>
         * 
         * <strong>example:</strong>
         * <p>[]</p>
         */
        @NameInMap("PlaybookTaskFlow")
        public String playbookTaskFlow;

        /**
         * <p>UUID of the playbook workflow.</p>
         * 
         * <strong>example:</strong>
         * <p>8ea81047-<strong><strong>-4481-</strong></strong>-fcd8557bf242</p>
         */
        @NameInMap("PlaybookTaskFlowUuid")
        public String playbookTaskFlowUuid;

        /**
         * <p>Type of the playbook, with values as follows:</p>
         * <ul>
         * <li><strong>preset</strong>: Predefined playbook.</li>
         * <li><strong>user</strong>: Custom playbook.</li>
         * <li><strong>component</strong>: Security response component.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>preset</p>
         */
        @NameInMap("PlaybookType")
        public String playbookType;

        /**
         * <p>UUID of the playbook.</p>
         * 
         * <strong>example:</strong>
         * <p>8db257d3-e2b2-44fd-b2cc-xxxxx</p>
         */
        @NameInMap("PlaybookUuid")
        public String playbookUuid;

        /**
         * <p>Version number of the playbook.</p>
         * 
         * <strong>example:</strong>
         * <p>36c9dcd6-<strong><strong>-4262-</strong></strong>-d508464ebd21</p>
         */
        @NameInMap("PlaybookVersion")
        public String playbookVersion;

        /**
         * <p>Update time (in milliseconds).</p>
         * 
         * <strong>example:</strong>
         * <p>1731378251000</p>
         */
        @NameInMap("UpdateTime")
        public Long updateTime;

        public static GetPlaybookResponseBodyPlaybook build(java.util.Map<String, ?> map) throws Exception {
            GetPlaybookResponseBodyPlaybook self = new GetPlaybookResponseBodyPlaybook();
            return TeaModel.build(map, self);
        }

        public GetPlaybookResponseBodyPlaybook setCreateTime(Long createTime) {
            this.createTime = createTime;
            return this;
        }
        public Long getCreateTime() {
            return this.createTime;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookDescription(String playbookDescription) {
            this.playbookDescription = playbookDescription;
            return this;
        }
        public String getPlaybookDescription() {
            return this.playbookDescription;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookExtension(String playbookExtension) {
            this.playbookExtension = playbookExtension;
            return this;
        }
        public String getPlaybookExtension() {
            return this.playbookExtension;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookInputConfigs(java.util.List<FieldInputConfig> playbookInputConfigs) {
            this.playbookInputConfigs = playbookInputConfigs;
            return this;
        }
        public java.util.List<FieldInputConfig> getPlaybookInputConfigs() {
            return this.playbookInputConfigs;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookName(String playbookName) {
            this.playbookName = playbookName;
            return this;
        }
        public String getPlaybookName() {
            return this.playbookName;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookOutputConfigs(java.util.List<FieldOutputConfig> playbookOutputConfigs) {
            this.playbookOutputConfigs = playbookOutputConfigs;
            return this;
        }
        public java.util.List<FieldOutputConfig> getPlaybookOutputConfigs() {
            return this.playbookOutputConfigs;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookParamType(String playbookParamType) {
            this.playbookParamType = playbookParamType;
            return this;
        }
        public String getPlaybookParamType() {
            return this.playbookParamType;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookParamsExample(String playbookParamsExample) {
            this.playbookParamsExample = playbookParamsExample;
            return this;
        }
        public String getPlaybookParamsExample() {
            return this.playbookParamsExample;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookStatus(Integer playbookStatus) {
            this.playbookStatus = playbookStatus;
            return this;
        }
        public Integer getPlaybookStatus() {
            return this.playbookStatus;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookTaskFlow(String playbookTaskFlow) {
            this.playbookTaskFlow = playbookTaskFlow;
            return this;
        }
        public String getPlaybookTaskFlow() {
            return this.playbookTaskFlow;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookTaskFlowUuid(String playbookTaskFlowUuid) {
            this.playbookTaskFlowUuid = playbookTaskFlowUuid;
            return this;
        }
        public String getPlaybookTaskFlowUuid() {
            return this.playbookTaskFlowUuid;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookType(String playbookType) {
            this.playbookType = playbookType;
            return this;
        }
        public String getPlaybookType() {
            return this.playbookType;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookUuid(String playbookUuid) {
            this.playbookUuid = playbookUuid;
            return this;
        }
        public String getPlaybookUuid() {
            return this.playbookUuid;
        }

        public GetPlaybookResponseBodyPlaybook setPlaybookVersion(String playbookVersion) {
            this.playbookVersion = playbookVersion;
            return this;
        }
        public String getPlaybookVersion() {
            return this.playbookVersion;
        }

        public GetPlaybookResponseBodyPlaybook setUpdateTime(Long updateTime) {
            this.updateTime = updateTime;
            return this;
        }
        public Long getUpdateTime() {
            return this.updateTime;
        }

    }

}
