// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.cloudauth20190307.models;

import com.aliyun.tea.*;

public class DescribeListAntCloudAuthScenesResponseBody extends TeaModel {
    /**
     * <p>ID of this request.</p>
     * 
     * <strong>example:</strong>
     * <p>CC1AB3F5-22A2-589F-ABDD-B766694AA671</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>List of scenarios.</p>
     */
    @NameInMap("Scenes")
    public java.util.List<DescribeListAntCloudAuthScenesResponseBodyScenes> scenes;

    public static DescribeListAntCloudAuthScenesResponseBody build(java.util.Map<String, ?> map) throws Exception {
        DescribeListAntCloudAuthScenesResponseBody self = new DescribeListAntCloudAuthScenesResponseBody();
        return TeaModel.build(map, self);
    }

    public DescribeListAntCloudAuthScenesResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public DescribeListAntCloudAuthScenesResponseBody setScenes(java.util.List<DescribeListAntCloudAuthScenesResponseBodyScenes> scenes) {
        this.scenes = scenes;
        return this;
    }
    public java.util.List<DescribeListAntCloudAuthScenesResponseBodyScenes> getScenes() {
        return this.scenes;
    }

    public static class DescribeListAntCloudAuthScenesResponseBodyScenes extends TeaModel {
        /**
         * <p>Application ID.</p>
         * 
         * <strong>example:</strong>
         * <p>2a3a13b6-ee85-457e-bd15-b48115cb396e</p>
         */
        @NameInMap("AppId")
        public Long appId;

        /**
         * <p>Whether to enable binding to a mini program:</p>
         * <ul>
         * <li><strong>Y</strong>: Enabled</li>
         * <li><strong>N (default)</strong>: Not enabled</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>Y</p>
         */
        @NameInMap("BindMiniProgram")
        public String bindMiniProgram;

        /**
         * <p>Creation time.</p>
         * 
         * <strong>example:</strong>
         * <p>1260051251634779</p>
         */
        @NameInMap("CreateTime")
        public String createTime;

        /**
         * <p>Creator.</p>
         * 
         * <strong>example:</strong>
         * <p>189884094677xxxx</p>
         */
        @NameInMap("Creator")
        public String creator;

        @NameInMap("DeviceRiskPlus")
        public String deviceRiskPlus;

        /**
         * <p>Bound domain.</p>
         * 
         * <strong>example:</strong>
         * <p><a href="http://www.ddos.com">www.ddos.com</a></p>
         */
        @NameInMap("Domain")
        public String domain;

        /**
         * <p>Mini program name.</p>
         * 
         * <strong>example:</strong>
         * <p>测试APP</p>
         */
        @NameInMap("MiniProgramName")
        public String miniProgramName;

        /**
         * <p>Modifier.</p>
         * 
         * <strong>example:</strong>
         * <p>189884094677xxxx</p>
         */
        @NameInMap("Modifier")
        public String modifier;

        /**
         * <p>Platform for binding the mini program:</p>
         * <ul>
         * <li><strong>WECHAT</strong>: WeChat</li>
         * <li><strong>ALIPAY</strong>: Alipay</li>
         * <li><strong>TIKTOK</strong>: TikTok</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>WECHAT</p>
         */
        @NameInMap("Platform")
        public String platform;

        @NameInMap("ReturnPicCount")
        public Long returnPicCount;

        @NameInMap("ReturnVideoLength")
        public Long returnVideoLength;

        /**
         * <p>Scenario ID.</p>
         * 
         * <strong>example:</strong>
         * <p>100001xxxx</p>
         */
        @NameInMap("SceneId")
        public Long sceneId;

        /**
         * <p>Scenario name.</p>
         * 
         * <strong>example:</strong>
         * <p>测试场景</p>
         */
        @NameInMap("SceneName")
        public String sceneName;

        /**
         * <p>Whether it is enabled, with 1 indicating yes.</p>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("Status")
        public Integer status;

        /**
         * <p>Whether to deliver the files generated by the authentication to the customer\&quot;s OSS:</p>
         * <ul>
         * <li><strong>Y</strong>: Enabled</li>
         * <li><strong>N</strong>: Disabled</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>Y</p>
         */
        @NameInMap("StoreImage")
        public String storeImage;

        /**
         * <p>The last update time of the instance.</p>
         * 
         * <strong>example:</strong>
         * <p>1260051251634779</p>
         */
        @NameInMap("UpdateTime")
        public String updateTime;

        public static DescribeListAntCloudAuthScenesResponseBodyScenes build(java.util.Map<String, ?> map) throws Exception {
            DescribeListAntCloudAuthScenesResponseBodyScenes self = new DescribeListAntCloudAuthScenesResponseBodyScenes();
            return TeaModel.build(map, self);
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setAppId(Long appId) {
            this.appId = appId;
            return this;
        }
        public Long getAppId() {
            return this.appId;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setBindMiniProgram(String bindMiniProgram) {
            this.bindMiniProgram = bindMiniProgram;
            return this;
        }
        public String getBindMiniProgram() {
            return this.bindMiniProgram;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setCreateTime(String createTime) {
            this.createTime = createTime;
            return this;
        }
        public String getCreateTime() {
            return this.createTime;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setCreator(String creator) {
            this.creator = creator;
            return this;
        }
        public String getCreator() {
            return this.creator;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setDeviceRiskPlus(String deviceRiskPlus) {
            this.deviceRiskPlus = deviceRiskPlus;
            return this;
        }
        public String getDeviceRiskPlus() {
            return this.deviceRiskPlus;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setDomain(String domain) {
            this.domain = domain;
            return this;
        }
        public String getDomain() {
            return this.domain;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setMiniProgramName(String miniProgramName) {
            this.miniProgramName = miniProgramName;
            return this;
        }
        public String getMiniProgramName() {
            return this.miniProgramName;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setModifier(String modifier) {
            this.modifier = modifier;
            return this;
        }
        public String getModifier() {
            return this.modifier;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setPlatform(String platform) {
            this.platform = platform;
            return this;
        }
        public String getPlatform() {
            return this.platform;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setReturnPicCount(Long returnPicCount) {
            this.returnPicCount = returnPicCount;
            return this;
        }
        public Long getReturnPicCount() {
            return this.returnPicCount;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setReturnVideoLength(Long returnVideoLength) {
            this.returnVideoLength = returnVideoLength;
            return this;
        }
        public Long getReturnVideoLength() {
            return this.returnVideoLength;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setSceneId(Long sceneId) {
            this.sceneId = sceneId;
            return this;
        }
        public Long getSceneId() {
            return this.sceneId;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setSceneName(String sceneName) {
            this.sceneName = sceneName;
            return this;
        }
        public String getSceneName() {
            return this.sceneName;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setStatus(Integer status) {
            this.status = status;
            return this;
        }
        public Integer getStatus() {
            return this.status;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setStoreImage(String storeImage) {
            this.storeImage = storeImage;
            return this;
        }
        public String getStoreImage() {
            return this.storeImage;
        }

        public DescribeListAntCloudAuthScenesResponseBodyScenes setUpdateTime(String updateTime) {
            this.updateTime = updateTime;
            return this;
        }
        public String getUpdateTime() {
            return this.updateTime;
        }

    }

}
