// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sas20181203.models;

import com.aliyun.tea.*;

public class DescribeNsasSuspEventTypeResponseBody extends TeaModel {
    /**
     * <p>The list of security alerting Alarm Metric information.</p>
     */
    @NameInMap("EventTypes")
    public java.util.List<DescribeNsasSuspEventTypeResponseBodyEventTypes> eventTypes;

    /**
     * <p>The request ID, which is a unique identifier generated by Alibaba Cloud for the request. You can use this ID to troubleshoot issues.</p>
     * 
     * <strong>example:</strong>
     * <p>9FBC6E47-7508-58C9-9E76-528E118CB1CC</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    public static DescribeNsasSuspEventTypeResponseBody build(java.util.Map<String, ?> map) throws Exception {
        DescribeNsasSuspEventTypeResponseBody self = new DescribeNsasSuspEventTypeResponseBody();
        return TeaModel.build(map, self);
    }

    public DescribeNsasSuspEventTypeResponseBody setEventTypes(java.util.List<DescribeNsasSuspEventTypeResponseBodyEventTypes> eventTypes) {
        this.eventTypes = eventTypes;
        return this;
    }
    public java.util.List<DescribeNsasSuspEventTypeResponseBodyEventTypes> getEventTypes() {
        return this.eventTypes;
    }

    public DescribeNsasSuspEventTypeResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public static class DescribeNsasSuspEventTypeResponseBodyEventTypes extends TeaModel {
        /**
         * <p>The name of the security alerting Alarm Metric.</p>
         * 
         * <strong>example:</strong>
         * <p>Unusual Logon</p>
         */
        @NameInMap("Name")
        public String name;

        /**
         * <p>The number of assets associated with the security alert.</p>
         * 
         * <strong>example:</strong>
         * <p>22</p>
         */
        @NameInMap("SuspEventCount")
        public Integer suspEventCount;

        /**
         * <p>The security alerting Alarm Metric.</p>
         * 
         * <strong>example:</strong>
         * <p>Unusual Logon</p>
         */
        @NameInMap("Type")
        public String type;

        public static DescribeNsasSuspEventTypeResponseBodyEventTypes build(java.util.Map<String, ?> map) throws Exception {
            DescribeNsasSuspEventTypeResponseBodyEventTypes self = new DescribeNsasSuspEventTypeResponseBodyEventTypes();
            return TeaModel.build(map, self);
        }

        public DescribeNsasSuspEventTypeResponseBodyEventTypes setName(String name) {
            this.name = name;
            return this;
        }
        public String getName() {
            return this.name;
        }

        public DescribeNsasSuspEventTypeResponseBodyEventTypes setSuspEventCount(Integer suspEventCount) {
            this.suspEventCount = suspEventCount;
            return this;
        }
        public Integer getSuspEventCount() {
            return this.suspEventCount;
        }

        public DescribeNsasSuspEventTypeResponseBodyEventTypes setType(String type) {
            this.type = type;
            return this;
        }
        public String getType() {
            return this.type;
        }

    }

}
