// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sas20181203.models;

import com.aliyun.tea.*;

public class GetAttackPathSensitiveAssetConfigResponseBody extends TeaModel {
    /**
     * <p>The attack path sensitive asset configuration data.</p>
     */
    @NameInMap("AttackPathSensitiveAssetConfig")
    public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig attackPathSensitiveAssetConfig;

    /**
     * <p>The request ID, which is a unique identifier generated by Alibaba Cloud for this request. You can use the ID to troubleshoot issues.</p>
     * 
     * <strong>example:</strong>
     * <p>3956048F-9D73-5EDB-834B-4827BB48****</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    public static GetAttackPathSensitiveAssetConfigResponseBody build(java.util.Map<String, ?> map) throws Exception {
        GetAttackPathSensitiveAssetConfigResponseBody self = new GetAttackPathSensitiveAssetConfigResponseBody();
        return TeaModel.build(map, self);
    }

    public GetAttackPathSensitiveAssetConfigResponseBody setAttackPathSensitiveAssetConfig(GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig attackPathSensitiveAssetConfig) {
        this.attackPathSensitiveAssetConfig = attackPathSensitiveAssetConfig;
        return this;
    }
    public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig getAttackPathSensitiveAssetConfig() {
        return this.attackPathSensitiveAssetConfig;
    }

    public GetAttackPathSensitiveAssetConfigResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public static class GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList extends TeaModel {
        /**
         * <p>The subtype of the cloud service asset.</p>
         * 
         * <strong>example:</strong>
         * <p>0</p>
         */
        @NameInMap("AssetSubType")
        public Integer assetSubType;

        /**
         * <p>The type of the cloud service asset.</p>
         * 
         * <strong>example:</strong>
         * <p>17</p>
         */
        @NameInMap("AssetType")
        public Integer assetType;

        /**
         * <p>The instance ID of the cloud service asset.</p>
         * 
         * <strong>example:</strong>
         * <p>i-bp174zui735kvf3v****</p>
         */
        @NameInMap("InstanceId")
        public String instanceId;

        /**
         * <p>The name of the cloud service asset instance.</p>
         * 
         * <strong>example:</strong>
         * <p>test</p>
         */
        @NameInMap("InstanceName")
        public String instanceName;

        /**
         * <p>The region ID of the cloud service asset instance.</p>
         * 
         * <strong>example:</strong>
         * <p>cn-hangzhou</p>
         */
        @NameInMap("RegionId")
        public String regionId;

        /**
         * <p>The vendor of the cloud service asset.</p>
         * 
         * <strong>example:</strong>
         * <p>4</p>
         */
        @NameInMap("Vendor")
        public Integer vendor;

        public static GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList build(java.util.Map<String, ?> map) throws Exception {
            GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList self = new GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList();
            return TeaModel.build(map, self);
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList setAssetSubType(Integer assetSubType) {
            this.assetSubType = assetSubType;
            return this;
        }
        public Integer getAssetSubType() {
            return this.assetSubType;
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList setAssetType(Integer assetType) {
            this.assetType = assetType;
            return this;
        }
        public Integer getAssetType() {
            return this.assetType;
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList setInstanceId(String instanceId) {
            this.instanceId = instanceId;
            return this;
        }
        public String getInstanceId() {
            return this.instanceId;
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList setInstanceName(String instanceName) {
            this.instanceName = instanceName;
            return this;
        }
        public String getInstanceName() {
            return this.instanceName;
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList setRegionId(String regionId) {
            this.regionId = regionId;
            return this;
        }
        public String getRegionId() {
            return this.regionId;
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList setVendor(Integer vendor) {
            this.vendor = vendor;
            return this;
        }
        public Integer getVendor() {
            return this.vendor;
        }

    }

    public static class GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig extends TeaModel {
        /**
         * <p>The list of cloud service assets in the attack path.</p>
         */
        @NameInMap("AttackPathAssetList")
        public java.util.List<GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList> attackPathAssetList;

        /**
         * <p>The ID of the attack path sensitive asset settings.</p>
         * 
         * <strong>example:</strong>
         * <p>apsac-123</p>
         */
        @NameInMap("AttackPathSensitiveAssetConfigId")
        public String attackPathSensitiveAssetConfigId;

        /**
         * <p>The configuration type. Valid values:</p>
         * <ul>
         * <li>asset_instance: asset.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>asset_instance</p>
         */
        @NameInMap("ConfigType")
        public String configType;

        public static GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig build(java.util.Map<String, ?> map) throws Exception {
            GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig self = new GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig();
            return TeaModel.build(map, self);
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig setAttackPathAssetList(java.util.List<GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList> attackPathAssetList) {
            this.attackPathAssetList = attackPathAssetList;
            return this;
        }
        public java.util.List<GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfigAttackPathAssetList> getAttackPathAssetList() {
            return this.attackPathAssetList;
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig setAttackPathSensitiveAssetConfigId(String attackPathSensitiveAssetConfigId) {
            this.attackPathSensitiveAssetConfigId = attackPathSensitiveAssetConfigId;
            return this;
        }
        public String getAttackPathSensitiveAssetConfigId() {
            return this.attackPathSensitiveAssetConfigId;
        }

        public GetAttackPathSensitiveAssetConfigResponseBodyAttackPathSensitiveAssetConfig setConfigType(String configType) {
            this.configType = configType;
            return this;
        }
        public String getConfigType() {
            return this.configType;
        }

    }

}
