// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sas20181203.models;

import com.aliyun.tea.*;

public class ListKspmInstancesResponseBody extends TeaModel {
    /**
     * <p>List of Kubernetes asset information.</p>
     */
    @NameInMap("Instances")
    public java.util.List<ListKspmInstancesResponseBodyInstances> instances;

    /**
     * <p>Page information for pagination queries.</p>
     */
    @NameInMap("PageInfo")
    public ListKspmInstancesResponseBodyPageInfo pageInfo;

    /**
     * <p>The ID of this call request, a unique identifier generated by Alibaba Cloud for the request, which can be used to troubleshoot and pinpoint issues.</p>
     * 
     * <strong>example:</strong>
     * <p>7532B7EE-7CE7-5F4D-BF04-B12447DDCAE1</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>Indicates whether the API call was successful. Values:</p>
     * <ul>
     * <li><strong>true</strong>: Success</li>
     * <li><strong>false</strong>: Failure</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>true</p>
     */
    @NameInMap("Success")
    public Boolean success;

    public static ListKspmInstancesResponseBody build(java.util.Map<String, ?> map) throws Exception {
        ListKspmInstancesResponseBody self = new ListKspmInstancesResponseBody();
        return TeaModel.build(map, self);
    }

    public ListKspmInstancesResponseBody setInstances(java.util.List<ListKspmInstancesResponseBodyInstances> instances) {
        this.instances = instances;
        return this;
    }
    public java.util.List<ListKspmInstancesResponseBodyInstances> getInstances() {
        return this.instances;
    }

    public ListKspmInstancesResponseBody setPageInfo(ListKspmInstancesResponseBodyPageInfo pageInfo) {
        this.pageInfo = pageInfo;
        return this;
    }
    public ListKspmInstancesResponseBodyPageInfo getPageInfo() {
        return this.pageInfo;
    }

    public ListKspmInstancesResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public ListKspmInstancesResponseBody setSuccess(Boolean success) {
        this.success = success;
        return this;
    }
    public Boolean getSuccess() {
        return this.success;
    }

    public static class ListKspmInstancesResponseBodyInstances extends TeaModel {
        /**
         * <p>Indicates whether the asset has security alarms. Values:</p>
         * <ul>
         * <li><strong>YES</strong>: There are security alarms</li>
         * <li><strong>NO</strong>: There are no security alarms</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>NO</p>
         */
        @NameInMap("AlarmStatus")
        public String alarmStatus;

        /**
         * <p>The subtype of the asset.</p>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("AssetSubType")
        public String assetSubType;

        /**
         * <p>The name of the asset subtype.</p>
         * 
         * <strong>example:</strong>
         * <p>Pod</p>
         */
        @NameInMap("AssetSubTypeName")
        public String assetSubTypeName;

        /**
         * <p>The type of the asset.</p>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("AssetType")
        public Integer assetType;

        /**
         * <p>The name of the asset type.</p>
         * 
         * <strong>example:</strong>
         * <p>Workload</p>
         */
        @NameInMap("AssetTypeName")
        public String assetTypeName;

        /**
         * <p>The timestamp when the instance was created. Unit: milliseconds.</p>
         * 
         * <strong>example:</strong>
         * <p>1607365213000</p>
         */
        @NameInMap("CreatedTime")
        public Long createdTime;

        /**
         * <p>The instance ID.</p>
         * 
         * <strong>example:</strong>
         * <p>rm-uf6t6u05n6g48****</p>
         */
        @NameInMap("InstanceId")
        public String instanceId;

        /**
         * <p>The name of the instance.</p>
         * 
         * <strong>example:</strong>
         * <p>yztest-l***</p>
         */
        @NameInMap("InstanceName")
        public String instanceName;

        /**
         * <p>The public IP address of the instance.</p>
         * 
         * <strong>example:</strong>
         * <p>1.2.XX.XX</p>
         */
        @NameInMap("InternetIp")
        public String internetIp;

        /**
         * <p>The ID of the region where the asset is located.</p>
         * 
         * <strong>example:</strong>
         * <p>cn-hanghzou</p>
         */
        @NameInMap("RegionId")
        public String regionId;

        /**
         * <p>Indicates whether the asset has security risks. Values:</p>
         * <ul>
         * <li><strong>YES</strong>: There are security risks</li>
         * <li><strong>NO</strong>: There are no security risks</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>NO</p>
         */
        @NameInMap("RiskStatus")
        public String riskStatus;

        /**
         * <p>Security information of the asset.</p>
         * 
         * <strong>example:</strong>
         * <p>{\&quot;seriousNum\&quot;:0,\&quot;appNum\&quot;:0,\&quot;baselineMedium\&quot;:0,\&quot;remindNum\&quot;:0,\&quot;imageVulNntf\&quot;:0,\&quot;cveNum\&quot;:0,\&quot;vul\&quot;:0,\&quot;uuid\&quot;:\&quot;rm-uf6t6u05n6g485o70\&quot;,\&quot;emgNum\&quot;:0,\&quot;weakPWNum\&quot;:0,\&quot;imageMaliciousFileRemind\&quot;:0,\&quot;imageBaselineMedium\&quot;:0,\&quot;laterVulCount\&quot;:0,\&quot;cmsNum\&quot;:0,\&quot;imageMaliciousFileSerious\&quot;:0,\&quot;agentlessMalicious\&quot;:0,\&quot;suspNum\&quot;:0,\&quot;imageBaselineHigh\&quot;:0,\&quot;asapVulCount\&quot;:0,\&quot;imageVulLater\&quot;:0,\&quot;agentlessAll\&quot;:0,\&quot;sysNum\&quot;:0,\&quot;containerLater\&quot;:0,\&quot;containerSuspicious\&quot;:0,\&quot;imageBaselineNum\&quot;:0,\&quot;newSuspicious\&quot;:0,\&quot;nntfVulCount\&quot;:0,\&quot;scaNum\&quot;:0,\&quot;containerNntf\&quot;:0,\&quot;health\&quot;:0,\&quot;trojan\&quot;:0,\&quot;suspicious\&quot;:0,\&quot;imageMaliciousFileSuspicious\&quot;:0,\&quot;containerRemind\&quot;:0,\&quot;baselineLow\&quot;:0,\&quot;imageVulAsap\&quot;:0,\&quot;imageBaselineLow\&quot;:0,\&quot;containerAsap\&quot;:0,\&quot;agentlessBaseline\&quot;:0,\&quot;agentlessVulSca\&quot;:0,\&quot;agentlessVulCve\&quot;:0,\&quot;containerSerious\&quot;:0,\&quot;baselineHigh\&quot;:0,\&quot;account\&quot;:0,\&quot;baselineNum\&quot;:6}</p>
         */
        @NameInMap("SecurityInfo")
        public String securityInfo;

        /**
         * <p>List of resource tags.</p>
         */
        @NameInMap("Tags")
        public java.util.List<String> tags;

        /**
         * <p>The vendor of the asset. This value is fixed at <strong>200</strong>.</p>
         * 
         * <strong>example:</strong>
         * <p>200</p>
         */
        @NameInMap("Vendor")
        public Integer vendor;

        public static ListKspmInstancesResponseBodyInstances build(java.util.Map<String, ?> map) throws Exception {
            ListKspmInstancesResponseBodyInstances self = new ListKspmInstancesResponseBodyInstances();
            return TeaModel.build(map, self);
        }

        public ListKspmInstancesResponseBodyInstances setAlarmStatus(String alarmStatus) {
            this.alarmStatus = alarmStatus;
            return this;
        }
        public String getAlarmStatus() {
            return this.alarmStatus;
        }

        public ListKspmInstancesResponseBodyInstances setAssetSubType(String assetSubType) {
            this.assetSubType = assetSubType;
            return this;
        }
        public String getAssetSubType() {
            return this.assetSubType;
        }

        public ListKspmInstancesResponseBodyInstances setAssetSubTypeName(String assetSubTypeName) {
            this.assetSubTypeName = assetSubTypeName;
            return this;
        }
        public String getAssetSubTypeName() {
            return this.assetSubTypeName;
        }

        public ListKspmInstancesResponseBodyInstances setAssetType(Integer assetType) {
            this.assetType = assetType;
            return this;
        }
        public Integer getAssetType() {
            return this.assetType;
        }

        public ListKspmInstancesResponseBodyInstances setAssetTypeName(String assetTypeName) {
            this.assetTypeName = assetTypeName;
            return this;
        }
        public String getAssetTypeName() {
            return this.assetTypeName;
        }

        public ListKspmInstancesResponseBodyInstances setCreatedTime(Long createdTime) {
            this.createdTime = createdTime;
            return this;
        }
        public Long getCreatedTime() {
            return this.createdTime;
        }

        public ListKspmInstancesResponseBodyInstances setInstanceId(String instanceId) {
            this.instanceId = instanceId;
            return this;
        }
        public String getInstanceId() {
            return this.instanceId;
        }

        public ListKspmInstancesResponseBodyInstances setInstanceName(String instanceName) {
            this.instanceName = instanceName;
            return this;
        }
        public String getInstanceName() {
            return this.instanceName;
        }

        public ListKspmInstancesResponseBodyInstances setInternetIp(String internetIp) {
            this.internetIp = internetIp;
            return this;
        }
        public String getInternetIp() {
            return this.internetIp;
        }

        public ListKspmInstancesResponseBodyInstances setRegionId(String regionId) {
            this.regionId = regionId;
            return this;
        }
        public String getRegionId() {
            return this.regionId;
        }

        public ListKspmInstancesResponseBodyInstances setRiskStatus(String riskStatus) {
            this.riskStatus = riskStatus;
            return this;
        }
        public String getRiskStatus() {
            return this.riskStatus;
        }

        public ListKspmInstancesResponseBodyInstances setSecurityInfo(String securityInfo) {
            this.securityInfo = securityInfo;
            return this;
        }
        public String getSecurityInfo() {
            return this.securityInfo;
        }

        public ListKspmInstancesResponseBodyInstances setTags(java.util.List<String> tags) {
            this.tags = tags;
            return this;
        }
        public java.util.List<String> getTags() {
            return this.tags;
        }

        public ListKspmInstancesResponseBodyInstances setVendor(Integer vendor) {
            this.vendor = vendor;
            return this;
        }
        public Integer getVendor() {
            return this.vendor;
        }

    }

    public static class ListKspmInstancesResponseBodyPageInfo extends TeaModel {
        /**
         * <p>The number of data items displayed on the current page.</p>
         * 
         * <strong>example:</strong>
         * <p>4</p>
         */
        @NameInMap("Count")
        public Integer count;

        /**
         * <p>The page number of the current page in a pagination query.</p>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("CurrentPage")
        public Integer currentPage;

        /**
         * <p>The maximum number of items to display per page in a pagination query.</p>
         * 
         * <strong>example:</strong>
         * <p>20</p>
         */
        @NameInMap("PageSize")
        public Integer pageSize;

        /**
         * <p>The total number of data items found.</p>
         * 
         * <strong>example:</strong>
         * <p>55</p>
         */
        @NameInMap("TotalCount")
        public Integer totalCount;

        public static ListKspmInstancesResponseBodyPageInfo build(java.util.Map<String, ?> map) throws Exception {
            ListKspmInstancesResponseBodyPageInfo self = new ListKspmInstancesResponseBodyPageInfo();
            return TeaModel.build(map, self);
        }

        public ListKspmInstancesResponseBodyPageInfo setCount(Integer count) {
            this.count = count;
            return this;
        }
        public Integer getCount() {
            return this.count;
        }

        public ListKspmInstancesResponseBodyPageInfo setCurrentPage(Integer currentPage) {
            this.currentPage = currentPage;
            return this;
        }
        public Integer getCurrentPage() {
            return this.currentPage;
        }

        public ListKspmInstancesResponseBodyPageInfo setPageSize(Integer pageSize) {
            this.pageSize = pageSize;
            return this;
        }
        public Integer getPageSize() {
            return this.pageSize;
        }

        public ListKspmInstancesResponseBodyPageInfo setTotalCount(Integer totalCount) {
            this.totalCount = totalCount;
            return this;
        }
        public Integer getTotalCount() {
            return this.totalCount;
        }

    }

}
