// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.sas20181203.models;

import com.aliyun.tea.*;

public class ListAegisForLingjunStatusResponseBody extends TeaModel {
    /**
     * <p>List of returned installation tasks.</p>
     */
    @NameInMap("InvokeTasks")
    public java.util.List<ListAegisForLingjunStatusResponseBodyInvokeTasks> invokeTasks;

    /**
     * <p>The ID of this request, which is a unique identifier generated by Alibaba Cloud for this request and can be used for troubleshooting and problem localization.</p>
     * 
     * <strong>example:</strong>
     * <p>F8B6F758-BCD4-597A-8A2C-DA5A552C****</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>Indicates whether the API call was successful. Values:</p>
     * <ul>
     * <li><strong>true</strong>: Success</li>
     * <li><strong>false</strong>: Failure</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>true</p>
     */
    @NameInMap("Success")
    public Boolean success;

    public static ListAegisForLingjunStatusResponseBody build(java.util.Map<String, ?> map) throws Exception {
        ListAegisForLingjunStatusResponseBody self = new ListAegisForLingjunStatusResponseBody();
        return TeaModel.build(map, self);
    }

    public ListAegisForLingjunStatusResponseBody setInvokeTasks(java.util.List<ListAegisForLingjunStatusResponseBodyInvokeTasks> invokeTasks) {
        this.invokeTasks = invokeTasks;
        return this;
    }
    public java.util.List<ListAegisForLingjunStatusResponseBodyInvokeTasks> getInvokeTasks() {
        return this.invokeTasks;
    }

    public ListAegisForLingjunStatusResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public ListAegisForLingjunStatusResponseBody setSuccess(Boolean success) {
        this.success = success;
        return this;
    }
    public Boolean getSuccess() {
        return this.success;
    }

    public static class ListAegisForLingjunStatusResponseBodyInvokeTasks extends TeaModel {
        /**
         * <p>Installation task ID for the Lingjun machine.</p>
         * 
         * <strong>example:</strong>
         * <p>t-bj05dlbzple****</p>
         */
        @NameInMap("InvokeId")
        public String invokeId;

        /**
         * <p>Installation processing result. Values:</p>
         * <ul>
         * <li>success: Installation successful</li>
         * <li>fail: Installation failed</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>success</p>
         */
        @NameInMap("Result")
        public String result;

        /**
         * <p>Installation status. Values:</p>
         * <ul>
         * <li><strong>1</strong>: Installation successful</li>
         * <li><strong>0</strong>: Installation failed</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("Status")
        public Integer status;

        /**
         * <p>Unique UUID for Lingjun bare metal.</p>
         * 
         * <strong>example:</strong>
         * <p>inet-8e3fbd56-122c-4011-b692-4d048076****</p>
         */
        @NameInMap("Uuid")
        public String uuid;

        public static ListAegisForLingjunStatusResponseBodyInvokeTasks build(java.util.Map<String, ?> map) throws Exception {
            ListAegisForLingjunStatusResponseBodyInvokeTasks self = new ListAegisForLingjunStatusResponseBodyInvokeTasks();
            return TeaModel.build(map, self);
        }

        public ListAegisForLingjunStatusResponseBodyInvokeTasks setInvokeId(String invokeId) {
            this.invokeId = invokeId;
            return this;
        }
        public String getInvokeId() {
            return this.invokeId;
        }

        public ListAegisForLingjunStatusResponseBodyInvokeTasks setResult(String result) {
            this.result = result;
            return this;
        }
        public String getResult() {
            return this.result;
        }

        public ListAegisForLingjunStatusResponseBodyInvokeTasks setStatus(Integer status) {
            this.status = status;
            return this;
        }
        public Integer getStatus() {
            return this.status;
        }

        public ListAegisForLingjunStatusResponseBodyInvokeTasks setUuid(String uuid) {
            this.uuid = uuid;
            return this;
        }
        public String getUuid() {
            return this.uuid;
        }

    }

}
