// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.dysmsapi20170525.models;

import com.aliyun.tea.*;

public class QuerySmsAuthorizationLetterResponseBody extends TeaModel {
    /**
     * <p>The details of the access denial. This parameter is returned only when the RAM check fails.</p>
     * 
     * <strong>example:</strong>
     * <p>无</p>
     */
    @NameInMap("AccessDeniedDetail")
    public String accessDeniedDetail;

    /**
     * <p>The status code of the request.</p>
     * <ul>
     * <li>The value OK indicates that the request was successful.</li>
     * <li>For other error codes, see the error code list in this topic or <a href="https://help.aliyun.com/document_detail/101346.html">API error codes</a>.</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>OK</p>
     */
    @NameInMap("Code")
    public String code;

    /**
     * <p>The information of the letters of authorization.</p>
     */
    @NameInMap("Data")
    public java.util.List<QuerySmsAuthorizationLetterResponseBodyData> data;

    /**
     * <p>The description of the status code.</p>
     * 
     * <strong>example:</strong>
     * <p>OK</p>
     */
    @NameInMap("Message")
    public String message;

    /**
     * <p>The ID of the request, which is a unique identifier generated by Alibaba Cloud for the request and can be used to troubleshoot and locate issues.</p>
     * 
     * <strong>example:</strong>
     * <p>25D5AFDE-8EBC-132E-8909-1FDC071D</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>Indicates whether the API call was successful. Valid values:</p>
     * <ul>
     * <li><strong>true</strong>: The call was successful.</li>
     * <li><strong>false</strong>: The call failed.</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>true</p>
     */
    @NameInMap("Success")
    public Boolean success;

    public static QuerySmsAuthorizationLetterResponseBody build(java.util.Map<String, ?> map) throws Exception {
        QuerySmsAuthorizationLetterResponseBody self = new QuerySmsAuthorizationLetterResponseBody();
        return TeaModel.build(map, self);
    }

    public QuerySmsAuthorizationLetterResponseBody setAccessDeniedDetail(String accessDeniedDetail) {
        this.accessDeniedDetail = accessDeniedDetail;
        return this;
    }
    public String getAccessDeniedDetail() {
        return this.accessDeniedDetail;
    }

    public QuerySmsAuthorizationLetterResponseBody setCode(String code) {
        this.code = code;
        return this;
    }
    public String getCode() {
        return this.code;
    }

    public QuerySmsAuthorizationLetterResponseBody setData(java.util.List<QuerySmsAuthorizationLetterResponseBodyData> data) {
        this.data = data;
        return this;
    }
    public java.util.List<QuerySmsAuthorizationLetterResponseBodyData> getData() {
        return this.data;
    }

    public QuerySmsAuthorizationLetterResponseBody setMessage(String message) {
        this.message = message;
        return this;
    }
    public String getMessage() {
        return this.message;
    }

    public QuerySmsAuthorizationLetterResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public QuerySmsAuthorizationLetterResponseBody setSuccess(Boolean success) {
        this.success = success;
        return this;
    }
    public Boolean getSuccess() {
        return this.success;
    }

    public static class QuerySmsAuthorizationLetterResponseBodyData extends TeaModel {
        /**
         * <p>The authorizing party.</p>
         * 
         * <strong>example:</strong>
         * <p>菜鸟网络科技有限公司</p>
         */
        @NameInMap("Authorization")
        public String authorization;

        /**
         * <p>The validity period of the letter of authorization. Format: YYYY-MM-DD~YYYY-MM-DD.</p>
         * 
         * <strong>example:</strong>
         * <p>2023-01-01~2026-01-01</p>
         */
        @NameInMap("AuthorizationLetterExpDate")
        public String authorizationLetterExpDate;

        /**
         * <p>The letter of authorization ID.</p>
         * 
         * <strong>example:</strong>
         * <p>10000******</p>
         */
        @NameInMap("AuthorizationLetterId")
        public Long authorizationLetterId;

        /**
         * <p>The name of the letter of authorization.</p>
         * 
         * <strong>example:</strong>
         * <p>菜鸟公司授权书</p>
         */
        @NameInMap("AuthorizationLetterName")
        public String authorizationLetterName;

        /**
         * <p>The URL of the letter of authorization file.</p>
         */
        @NameInMap("AuthorizationLetterPic")
        public String authorizationLetterPic;

        /**
         * <p>The unified social credit code of the authorizing party.</p>
         * 
         * <strong>example:</strong>
         * <p>9****************A</p>
         */
        @NameInMap("OrganizationCode")
        public String organizationCode;

        /**
         * <p>The authorized party.</p>
         * 
         * <strong>example:</strong>
         * <p>支付宝（中国）网络技术有限公司</p>
         */
        @NameInMap("ProxyAuthorization")
        public String proxyAuthorization;

        /**
         * <p>The authorized signature scope. If multiple signatures are included, the signatures are separated by Chinese enumeration commas (、).</p>
         * 
         * <strong>example:</strong>
         * <p>菜鸟网络、菜鸟驿站、菜鸟裹裹</p>
         */
        @NameInMap("SignScope")
        public String signScope;

        /**
         * <p>The status of the letter of authorization, which is related to the review status of the signature. Valid values:</p>
         * <ul>
         * <li><strong>INT</strong>: Pending review. The letter of authorization has been created. After you submit a signature application, it enters the review process.</li>
         * <li><strong>PASSED</strong>: Review passed. When a signature in the authorized signature scope of the letter of authorization passes the review, the status of the letter of authorization changes to PASSED.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>PASSED</p>
         */
        @NameInMap("State")
        public String state;

        /**
         * <p>The availability status of the letter of authorization, which is related to the validity period of the letter of authorization. Valid values:</p>
         * <ul>
         * <li><strong>VALID</strong>: Available. The letter of authorization is within the validity period.</li>
         * <li><strong>INVALID</strong>: Unavailable. The letter of authorization has expired.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>VALID</p>
         */
        @NameInMap("Status")
        public String status;

        public static QuerySmsAuthorizationLetterResponseBodyData build(java.util.Map<String, ?> map) throws Exception {
            QuerySmsAuthorizationLetterResponseBodyData self = new QuerySmsAuthorizationLetterResponseBodyData();
            return TeaModel.build(map, self);
        }

        public QuerySmsAuthorizationLetterResponseBodyData setAuthorization(String authorization) {
            this.authorization = authorization;
            return this;
        }
        public String getAuthorization() {
            return this.authorization;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setAuthorizationLetterExpDate(String authorizationLetterExpDate) {
            this.authorizationLetterExpDate = authorizationLetterExpDate;
            return this;
        }
        public String getAuthorizationLetterExpDate() {
            return this.authorizationLetterExpDate;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setAuthorizationLetterId(Long authorizationLetterId) {
            this.authorizationLetterId = authorizationLetterId;
            return this;
        }
        public Long getAuthorizationLetterId() {
            return this.authorizationLetterId;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setAuthorizationLetterName(String authorizationLetterName) {
            this.authorizationLetterName = authorizationLetterName;
            return this;
        }
        public String getAuthorizationLetterName() {
            return this.authorizationLetterName;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setAuthorizationLetterPic(String authorizationLetterPic) {
            this.authorizationLetterPic = authorizationLetterPic;
            return this;
        }
        public String getAuthorizationLetterPic() {
            return this.authorizationLetterPic;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setOrganizationCode(String organizationCode) {
            this.organizationCode = organizationCode;
            return this;
        }
        public String getOrganizationCode() {
            return this.organizationCode;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setProxyAuthorization(String proxyAuthorization) {
            this.proxyAuthorization = proxyAuthorization;
            return this;
        }
        public String getProxyAuthorization() {
            return this.proxyAuthorization;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setSignScope(String signScope) {
            this.signScope = signScope;
            return this;
        }
        public String getSignScope() {
            return this.signScope;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setState(String state) {
            this.state = state;
            return this;
        }
        public String getState() {
            return this.state;
        }

        public QuerySmsAuthorizationLetterResponseBodyData setStatus(String status) {
            this.status = status;
            return this;
        }
        public String getStatus() {
            return this.status;
        }

    }

}
