// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.rds20140815.models;

import com.aliyun.tea.*;

public class DescribeSQLServerUpgradeVersionsRequest extends TeaModel {
    /**
     * <p>This parameter ensures the idempotence of the request to prevent duplicate submissions. The value is generated by the client and must be unique across different requests.</p>
     * <p>The value consists of ASCII characters, contains no more than 64 characters, and must not include non-ASCII characters.</p>
     * 
     * <strong>example:</strong>
     * <p>ETnLKlblzczshOTUbOC****</p>
     */
    @NameInMap("ClientToken")
    public String clientToken;

    /**
     * <p>Instance ID. You can obtain it by invoking DescribeDBInstances.</p>
     * 
     * <strong>example:</strong>
     * <p>rm-xx1xxx2****</p>
     */
    @NameInMap("DBInstanceId")
    public String DBInstanceId;

    /**
     * <p>Database version to query. If instanceId is specified, the instance\&quot;s version overwrites this parameter.</p>
     * 
     * <strong>example:</strong>
     * <p>2016_web</p>
     */
    @NameInMap("EngineVersion")
    public String engineVersion;

    @NameInMap("OwnerId")
    public Long ownerId;

    @NameInMap("ResourceOwnerAccount")
    public String resourceOwnerAccount;

    @NameInMap("ResourceOwnerId")
    public Long resourceOwnerId;

    public static DescribeSQLServerUpgradeVersionsRequest build(java.util.Map<String, ?> map) throws Exception {
        DescribeSQLServerUpgradeVersionsRequest self = new DescribeSQLServerUpgradeVersionsRequest();
        return TeaModel.build(map, self);
    }

    public DescribeSQLServerUpgradeVersionsRequest setClientToken(String clientToken) {
        this.clientToken = clientToken;
        return this;
    }
    public String getClientToken() {
        return this.clientToken;
    }

    public DescribeSQLServerUpgradeVersionsRequest setDBInstanceId(String DBInstanceId) {
        this.DBInstanceId = DBInstanceId;
        return this;
    }
    public String getDBInstanceId() {
        return this.DBInstanceId;
    }

    public DescribeSQLServerUpgradeVersionsRequest setEngineVersion(String engineVersion) {
        this.engineVersion = engineVersion;
        return this;
    }
    public String getEngineVersion() {
        return this.engineVersion;
    }

    public DescribeSQLServerUpgradeVersionsRequest setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
        return this;
    }
    public Long getOwnerId() {
        return this.ownerId;
    }

    public DescribeSQLServerUpgradeVersionsRequest setResourceOwnerAccount(String resourceOwnerAccount) {
        this.resourceOwnerAccount = resourceOwnerAccount;
        return this;
    }
    public String getResourceOwnerAccount() {
        return this.resourceOwnerAccount;
    }

    public DescribeSQLServerUpgradeVersionsRequest setResourceOwnerId(Long resourceOwnerId) {
        this.resourceOwnerId = resourceOwnerId;
        return this;
    }
    public Long getResourceOwnerId() {
        return this.resourceOwnerId;
    }

}
