// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.fc_open20210406.models;

import com.aliyun.tea.*;

public class ListServicesResponseBody extends TeaModel {
    /**
     * <p>The token used to obtain more results. If this parameter is left empty, all the results are returned.</p>
     * 
     * <strong>example:</strong>
     * <p>caeba0****be03f84eb48b699f0a4883</p>
     */
    @NameInMap("nextToken")
    public String nextToken;

    /**
     * <p>The queried services.</p>
     */
    @NameInMap("services")
    public java.util.List<ListServicesResponseBodyServices> services;

    public static ListServicesResponseBody build(java.util.Map<String, ?> map) throws Exception {
        ListServicesResponseBody self = new ListServicesResponseBody();
        return TeaModel.build(map, self);
    }

    public ListServicesResponseBody setNextToken(String nextToken) {
        this.nextToken = nextToken;
        return this;
    }
    public String getNextToken() {
        return this.nextToken;
    }

    public ListServicesResponseBody setServices(java.util.List<ListServicesResponseBodyServices> services) {
        this.services = services;
        return this;
    }
    public java.util.List<ListServicesResponseBodyServices> getServices() {
        return this.services;
    }

    public static class ListServicesResponseBodyServices extends TeaModel {
        /**
         * <p>The time when the service was created.</p>
         * 
         * <strong>example:</strong>
         * <p>2020-04-03T05:57:28Z</p>
         */
        @NameInMap("createdTime")
        public String createdTime;

        /**
         * <p>The description of the service.</p>
         * 
         * <strong>example:</strong>
         * <p>test_description</p>
         */
        @NameInMap("description")
        public String description;

        /**
         * <p>Indicates whether to allow functions to access the Internet. Valid values:</p>
         * <ul>
         * <li><strong>true</strong></li>
         * <li><strong>false</strong></li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>true</p>
         */
        @NameInMap("internetAccess")
        public Boolean internetAccess;

        /**
         * <p>The last time when the service was updated.</p>
         * 
         * <strong>example:</strong>
         * <p>2020-04-03T05:57:28Z</p>
         */
        @NameInMap("lastModifiedTime")
        public String lastModifiedTime;

        /**
         * <p>The logging configurations. Function Compute writes function execution logs to the specified Logstores.</p>
         */
        @NameInMap("logConfig")
        public LogConfig logConfig;

        /**
         * <p>The configurations of the File Storage NAS (NAS) file system. These configurations allow functions to access the specified NAS resources.</p>
         */
        @NameInMap("nasConfig")
        public NASConfig nasConfig;

        /**
         * <p>The Object Storage Service (OSS) mounting configurations.</p>
         */
        @NameInMap("ossMountConfig")
        public OSSMountConfig ossMountConfig;

        /**
         * <p>The Alibaba Cloud Resource Name (ARN) of the RAM role that is used to grant required permissions to Function Compute. The RAM role is used in the following scenarios:</p>
         * <ul>
         * <li>Send function execution logs to your Logstore.</li>
         * <li>Generate a token for a function to access other Alibaba Cloud resources during function execution.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>acs:ram::198613743****:role/fc-public-test</p>
         */
        @NameInMap("role")
        public String role;

        /**
         * <p>The ID generated by the system for each service, which is globally unique.</p>
         * 
         * <strong>example:</strong>
         * <p>c910061f-****-44e6-b659-***c</p>
         */
        @NameInMap("serviceId")
        public String serviceId;

        /**
         * <p>The name of the service.</p>
         * 
         * <strong>example:</strong>
         * <p>service_name</p>
         */
        @NameInMap("serviceName")
        public String serviceName;

        /**
         * <p>The configurations of Managed Service for OpenTelemetry. After you configure Managed Service for OpenTelemetry for functions in Function Compute, you can record the execution durations of requests and internal processing durations of functions, and view the cold start latencies. For more information, see <a href="https://help.aliyun.com/document_detail/189804.html">Overview</a>.</p>
         */
        @NameInMap("tracingConfig")
        public TracingConfig tracingConfig;

        /**
         * <p>Indicates whether service-linked role authorization is enabled. Valid values:</p>
         * <ul>
         * <li>true</li>
         * <li>false</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>true</p>
         */
        @NameInMap("useSLRAuthentication")
        public Boolean useSLRAuthentication;

        /**
         * <p>The configurations of virtual private clouds (VPCs). These configurations allow Function Compute to access the specified VPC resources.</p>
         */
        @NameInMap("vpcConfig")
        public VPCConfig vpcConfig;

        public static ListServicesResponseBodyServices build(java.util.Map<String, ?> map) throws Exception {
            ListServicesResponseBodyServices self = new ListServicesResponseBodyServices();
            return TeaModel.build(map, self);
        }

        public ListServicesResponseBodyServices setCreatedTime(String createdTime) {
            this.createdTime = createdTime;
            return this;
        }
        public String getCreatedTime() {
            return this.createdTime;
        }

        public ListServicesResponseBodyServices setDescription(String description) {
            this.description = description;
            return this;
        }
        public String getDescription() {
            return this.description;
        }

        public ListServicesResponseBodyServices setInternetAccess(Boolean internetAccess) {
            this.internetAccess = internetAccess;
            return this;
        }
        public Boolean getInternetAccess() {
            return this.internetAccess;
        }

        public ListServicesResponseBodyServices setLastModifiedTime(String lastModifiedTime) {
            this.lastModifiedTime = lastModifiedTime;
            return this;
        }
        public String getLastModifiedTime() {
            return this.lastModifiedTime;
        }

        public ListServicesResponseBodyServices setLogConfig(LogConfig logConfig) {
            this.logConfig = logConfig;
            return this;
        }
        public LogConfig getLogConfig() {
            return this.logConfig;
        }

        public ListServicesResponseBodyServices setNasConfig(NASConfig nasConfig) {
            this.nasConfig = nasConfig;
            return this;
        }
        public NASConfig getNasConfig() {
            return this.nasConfig;
        }

        public ListServicesResponseBodyServices setOssMountConfig(OSSMountConfig ossMountConfig) {
            this.ossMountConfig = ossMountConfig;
            return this;
        }
        public OSSMountConfig getOssMountConfig() {
            return this.ossMountConfig;
        }

        public ListServicesResponseBodyServices setRole(String role) {
            this.role = role;
            return this;
        }
        public String getRole() {
            return this.role;
        }

        public ListServicesResponseBodyServices setServiceId(String serviceId) {
            this.serviceId = serviceId;
            return this;
        }
        public String getServiceId() {
            return this.serviceId;
        }

        public ListServicesResponseBodyServices setServiceName(String serviceName) {
            this.serviceName = serviceName;
            return this;
        }
        public String getServiceName() {
            return this.serviceName;
        }

        public ListServicesResponseBodyServices setTracingConfig(TracingConfig tracingConfig) {
            this.tracingConfig = tracingConfig;
            return this;
        }
        public TracingConfig getTracingConfig() {
            return this.tracingConfig;
        }

        public ListServicesResponseBodyServices setUseSLRAuthentication(Boolean useSLRAuthentication) {
            this.useSLRAuthentication = useSLRAuthentication;
            return this;
        }
        public Boolean getUseSLRAuthentication() {
            return this.useSLRAuthentication;
        }

        public ListServicesResponseBodyServices setVpcConfig(VPCConfig vpcConfig) {
            this.vpcConfig = vpcConfig;
            return this;
        }
        public VPCConfig getVpcConfig() {
            return this.vpcConfig;
        }

    }

}
