// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.cas20200630.models;

import com.aliyun.tea.*;

public class CreateExternalCACertificateShrinkRequest extends TeaModel {
    /**
     * <p>Overrides CSR content or adds content to the CA certificate through API parameters.</p>
     */
    @NameInMap("ApiPassthrough")
    public String apiPassthroughShrink;

    /**
     * <p>The maximum validity period for issued certificates, as specified by the certMaxTime of the CA. Unit: days.</p>
     * 
     * <strong>example:</strong>
     * <p>30</p>
     */
    @NameInMap("CertMaxTime")
    public Integer certMaxTime;

    /**
     * <p>The certificate signing request. The CSR can contain the SubjectDN and custom extensions of the CA certificate. The SubjectKeyIdentifier, AuthorityKeyIdentifier, and CRLDistributionPoints certificate extensions are generated by the CA, and the values in the CSR are ignored.</p>
     * 
     * <strong>example:</strong>
     * <p>-----BEGIN CERTIFICATE REQUEST-----
     * MIIBczCCARgCAQAwgYoxFDASBgNVBAMMC2FsaXl1bi50ZXN0MQ0wCwYDVQQ
     * ...
     * vbIgMQIhAKHDWD6/WAMbtezAt4bysJ/BZIDz1jPWuUR5GV4TJ/mS
     * -----END CERTIFICATE REQUEST-----</p>
     */
    @NameInMap("Csr")
    public String csr;

    /**
     * <p>The instance ID of the external subordinate CA instance to activate.</p>
     * 
     * <strong>example:</strong>
     * <p>cas_deposit-cn-1234abcd</p>
     */
    @NameInMap("InstanceId")
    public String instanceId;

    /**
     * <p>The resource group ID.</p>
     * 
     * <strong>example:</strong>
     * <p>test</p>
     */
    @NameInMap("ResourceGroupId")
    public String resourceGroupId;

    /**
     * <p>The list of tags.</p>
     */
    @NameInMap("Tags")
    public java.util.List<CreateExternalCACertificateShrinkRequestTags> tags;

    /**
     * <p>The certificate validity period. Both relative time and absolute time are supported.</p>
     * <blockquote>
     * <p>Relative time: Supports the units of year, month, and day.</p>
     * </blockquote>
     * <ul>
     * <li>Year - y</li>
     * <li>Month - m</li>
     * <li>Day - d</li>
     * </ul>
     * <blockquote>
     * <p>Absolute time: Uses GMT time. Format: <code>yyyy-MM-dd\\&quot;T\\&quot;HH:mm:ss\\&quot;Z\\&quot;</code></p>
     * </blockquote>
     * <ul>
     * <li>Specify the end time - <code>$NotAfter</code></li>
     * <li>Specify the start time and end time - <code>$NotBefore/$NotAfter</code></li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>10y</p>
     */
    @NameInMap("Validity")
    public String validity;

    public static CreateExternalCACertificateShrinkRequest build(java.util.Map<String, ?> map) throws Exception {
        CreateExternalCACertificateShrinkRequest self = new CreateExternalCACertificateShrinkRequest();
        return TeaModel.build(map, self);
    }

    public CreateExternalCACertificateShrinkRequest setApiPassthroughShrink(String apiPassthroughShrink) {
        this.apiPassthroughShrink = apiPassthroughShrink;
        return this;
    }
    public String getApiPassthroughShrink() {
        return this.apiPassthroughShrink;
    }

    public CreateExternalCACertificateShrinkRequest setCertMaxTime(Integer certMaxTime) {
        this.certMaxTime = certMaxTime;
        return this;
    }
    public Integer getCertMaxTime() {
        return this.certMaxTime;
    }

    public CreateExternalCACertificateShrinkRequest setCsr(String csr) {
        this.csr = csr;
        return this;
    }
    public String getCsr() {
        return this.csr;
    }

    public CreateExternalCACertificateShrinkRequest setInstanceId(String instanceId) {
        this.instanceId = instanceId;
        return this;
    }
    public String getInstanceId() {
        return this.instanceId;
    }

    public CreateExternalCACertificateShrinkRequest setResourceGroupId(String resourceGroupId) {
        this.resourceGroupId = resourceGroupId;
        return this;
    }
    public String getResourceGroupId() {
        return this.resourceGroupId;
    }

    public CreateExternalCACertificateShrinkRequest setTags(java.util.List<CreateExternalCACertificateShrinkRequestTags> tags) {
        this.tags = tags;
        return this;
    }
    public java.util.List<CreateExternalCACertificateShrinkRequestTags> getTags() {
        return this.tags;
    }

    public CreateExternalCACertificateShrinkRequest setValidity(String validity) {
        this.validity = validity;
        return this;
    }
    public String getValidity() {
        return this.validity;
    }

    public static class CreateExternalCACertificateShrinkRequestTags extends TeaModel {
        /**
         * <p>The tag key.</p>
         * 
         * <strong>example:</strong>
         * <p>database</p>
         */
        @NameInMap("Key")
        public String key;

        /**
         * <p>The tag value.</p>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("Value")
        public String value;

        public static CreateExternalCACertificateShrinkRequestTags build(java.util.Map<String, ?> map) throws Exception {
            CreateExternalCACertificateShrinkRequestTags self = new CreateExternalCACertificateShrinkRequestTags();
            return TeaModel.build(map, self);
        }

        public CreateExternalCACertificateShrinkRequestTags setKey(String key) {
            this.key = key;
            return this;
        }
        public String getKey() {
            return this.key;
        }

        public CreateExternalCACertificateShrinkRequestTags setValue(String value) {
            this.value = value;
            return this;
        }
        public String getValue() {
            return this.value;
        }

    }

}
