// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.elasticsearch20170613.models;

import com.aliyun.tea.*;

public class CloseHttpsRequest extends TeaModel {
    /**
     * <p>A unique token generated by the client to guarantee the idempotency of the request. You can use the client to generate a token, but you must ensure that it is unique among different requests. The token can only contain ASCII characters and cannot exceed 64 characters in length.</p>
     */
    @NameInMap("clientToken")
    public String clientToken;

    public static CloseHttpsRequest build(java.util.Map<String, ?> map) throws Exception {
        CloseHttpsRequest self = new CloseHttpsRequest();
        return TeaModel.build(map, self);
    }

    public CloseHttpsRequest setClientToken(String clientToken) {
        this.clientToken = clientToken;
        return this;
    }
    public String getClientToken() {
        return this.clientToken;
    }

}
