// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.eventbridge20200401.models;

import com.aliyun.tea.*;

public class GenerateAgentDataSemanticsResponseBody extends TeaModel {
    /**
     * <p>The response code returned by the operation.</p>
     * 
     * <strong>example:</strong>
     * <p>Success</p>
     */
    @NameInMap("Code")
    public String code;

    /**
     * <p>The task creation result. If the task is created successfully, an empty object is returned with no additional business fields.</p>
     * 
     * <strong>example:</strong>
     * <p>{}</p>
     */
    @NameInMap("Data")
    public java.util.Map<String, ?> data;

    /**
     * <p>The response message. If the call fails, this parameter contains the error message.</p>
     * 
     * <strong>example:</strong>
     * <p>Data semantics generation task is already running.</p>
     */
    @NameInMap("Message")
    public String message;

    /**
     * <p>The unique request ID generated by Alibaba Cloud for this request.</p>
     * 
     * <strong>example:</strong>
     * <p>5DAF96FB-A4DF-548C-B8A1-F2A8D2F4****</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>Indicates whether the call was successful.</p>
     * 
     * <strong>example:</strong>
     * <p>true</p>
     */
    @NameInMap("Success")
    public Boolean success;

    public static GenerateAgentDataSemanticsResponseBody build(java.util.Map<String, ?> map) throws Exception {
        GenerateAgentDataSemanticsResponseBody self = new GenerateAgentDataSemanticsResponseBody();
        return TeaModel.build(map, self);
    }

    public GenerateAgentDataSemanticsResponseBody setCode(String code) {
        this.code = code;
        return this;
    }
    public String getCode() {
        return this.code;
    }

    public GenerateAgentDataSemanticsResponseBody setData(java.util.Map<String, ?> data) {
        this.data = data;
        return this;
    }
    public java.util.Map<String, ?> getData() {
        return this.data;
    }

    public GenerateAgentDataSemanticsResponseBody setMessage(String message) {
        this.message = message;
        return this;
    }
    public String getMessage() {
        return this.message;
    }

    public GenerateAgentDataSemanticsResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public GenerateAgentDataSemanticsResponseBody setSuccess(Boolean success) {
        this.success = success;
        return this;
    }
    public Boolean getSuccess() {
        return this.success;
    }

}
