// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.airegistry20260317.models;

import com.aliyun.tea.*;

public class UpdateSkillDraftResponseBody extends TeaModel {
    /**
     * <p>The unique request ID generated by Alibaba Cloud for this request.</p>
     * 
     * <strong>example:</strong>
     * <p>6F402E85-E6D9-5A79-9EAF-8A1B6DCE7F79</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    public static UpdateSkillDraftResponseBody build(java.util.Map<String, ?> map) throws Exception {
        UpdateSkillDraftResponseBody self = new UpdateSkillDraftResponseBody();
        return TeaModel.build(map, self);
    }

    public UpdateSkillDraftResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

}
