// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.cas20200407.models;

import com.aliyun.tea.*;

public class CreateCertificateForPackageRequestRequest extends TeaModel {
    /**
     * <p>The company name of the certificate application.</p>
     * <blockquote>
     * <p> This parameter is available only when you apply for OV certificates. For more information, see <a href="https://help.aliyun.com/document_detail/198289.html">Manage company profiles</a>. If you want to apply for a DV certificate, you do not need to add a company profile.</p>
     * </blockquote>
     * <p>If you specify a company name, the information about the company that is configured in the <strong>Information Management</strong> module is used. If you do not specify this parameter, the information about the most recent company that is added to the <strong>Information Management</strong> module is used.</p>
     * 
     * <strong>example:</strong>
     * <p>A company</p>
     */
    @NameInMap("CompanyName")
    public String companyName;

    /**
     * <p>The content of the certificate signing request (CSR) file that is manually generated by using OpenSSL or Keytool for the domain name. The key algorithm in the CSR file must be Rivest-Shamir-Adleman (RSA) or elliptic-curve cryptography (ECC), and the key length of the RSA algorithm must be greater than or equal to 2,048 characters. For more information about how to create a CSR file, see <a href="https://help.aliyun.com/document_detail/313297.html">Create a CSR file</a>. If you do not specify this parameter, Certificate Management Service automatically creates a CSR file.</p>
     * <p>A CSR file contains the information about your server and company. When you apply for a certificate, you must submit the CSR file to the CA. The CA signs the CSR file by using the private key of the root certificate and generates a public key file to issue your certificate.</p>
     * <blockquote>
     * <p> The \<em>\<em>CN\</em>\</em> field in CSR file specifies the domain name that is bound to the certificate. You must include the field in the parameter value.</p>
     * </blockquote>
     * 
     * <strong>example:</strong>
     * <p>-----BEGIN CERTIFICATE REQUEST----- ...... -----END CERTIFICATE REQUEST-----</p>
     */
    @NameInMap("Csr")
    public String csr;

    /**
     * <p>The domain name that you want to bind to the certificate. The domain name must meet the following requirements:</p>
     * <ul>
     * <li>The domain name must be a single domain name or a wildcard domain name. Example: <code>*.aliyundoc.com</code>.</li>
     * <li>You can specify multiple domain names. Separate multiple domain names with commas (,). You can specify a maximum of five domain names.</li>
     * <li>If you specify multiple domain names, the domain names must be only single domain names or only wildcard domain names. You cannot specify both single domain names and wildcard domain names.</li>
     * </ul>
     * <blockquote>
     * <p> If you want to bind multiple domain names to the certificate, you must specify this parameter. You must specify at least one of the Domain parameter and the \<em>\<em>Csr\</em>\</em> parameter. If you specify both the Domain parameter and the \<em>\<em>Csr\</em>\</em> parameter, the value of the \<em>\<em>CN\</em>\</em> field in the \<em>\<em>Csr\</em>\</em> parameter is used as the domain name that is bound to the certificate.</p>
     * </blockquote>
     * 
     * <strong>example:</strong>
     * <p>aliyundoc.com</p>
     */
    @NameInMap("Domain")
    public String domain;

    /**
     * <p>The email address of the applicant. After the CA receives your certificate application, the CA sends a verification email to the email address that you specify. You must log on to the mailbox, open the mail, and complete the verification of the domain name ownership based on the steps that are described in the email.</p>
     * <p>If you do not specify this parameter, the information about the most recent contact that is added to the <strong>Information Management</strong> module is used. For more information about how to add a contact to the <strong>Information Management</strong> module, see <a href="https://help.aliyun.com/document_detail/198262.html">Manage contacts</a>.</p>
     * 
     * <strong>example:</strong>
     * <p><a href="mailto:username@example.com">username@example.com</a></p>
     */
    @NameInMap("Email")
    public String email;

    /**
     * <p>The contact phone number of the applicant. CA staff can call the phone number to confirm the information in your certificate application.</p>
     * <p>If you do not specify this parameter, the information about the most recent contact that is added to the <strong>Information Management</strong> module is used. For more information about how to add a contact to the <strong>Information Management</strong> module, see <a href="https://help.aliyun.com/document_detail/198262.html">Manage contacts</a>.</p>
     * 
     * <strong>example:</strong>
     * <p>1390000****</p>
     */
    @NameInMap("Phone")
    public String phone;

    /**
     * <p>The specifications of the certificate that you want to apply for. Valid values:</p>
     * <ul>
     * <li><strong>digicert-free-1-free</strong> (default): DigiCert single-domain domain validated (DV) certificate, which is free and valid for 3 months. This value is available only on the China site (aliyun.com).</li>
     * <li><strong>symantec-free-1-free</strong>: DigiCert single-domain DV certificate, which is free and valid for 1 year. This value is available only on the China site (aliyun.com).</li>
     * <li><strong>symantec-dv-1-starter</strong>: DigiCert wildcard DV certificate.</li>
     * <li><strong>symantec-ov-1-personal</strong>: DigiCert single-domain organization validated (OV) certificate.</li>
     * <li><strong>symantec-ov-w-personal</strong>: DigiCert wildcard OV certificate.</li>
     * <li><strong>geotrust-dv-1-starter</strong>: GeoTrust single-domain DV certificate.</li>
     * <li><strong>geotrust-dv-w-starter</strong>: GeoTrust wildcard DV certificate.</li>
     * <li><strong>geotrust-ov-1-personal</strong>: GeoTrust single-domain OV certificate.</li>
     * <li><strong>geotrust-ov-w-personal</strong>: GeoTrust wildcard OV certificate.</li>
     * <li><strong>globalsign-dv-1-personal</strong>: GlobalSign single-domain DV certificate.</li>
     * <li><strong>globalsign-dv-w-advanced</strong>: GlobalSign wildcard DV certificate.</li>
     * <li><strong>globalsign-ov-1-personal</strong>: GlobalSign single-domain OV certificate.</li>
     * <li><strong>globalsign-ov-w-advanced</strong>: GlobalSign wildcard OV certificate.</li>
     * <li><strong>cfca-ov-1-personal</strong>: China Financial Certification Authority (CFCA) single-domain OV certificate, available only on the China site (aliyun.com).</li>
     * <li><strong>cfca-ev-w-advanced</strong>: CFCA wildcard OV certificate, available only on the China site (aliyun.com).</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>symantec-free-1-free</p>
     */
    @NameInMap("ProductCode")
    public String productCode;

    /**
     * <p>The list of tags.</p>
     */
    @NameInMap("Tags")
    public java.util.List<CreateCertificateForPackageRequestRequestTags> tags;

    /**
     * <p>The name of the applicant.</p>
     * <p>If you do not specify this parameter, the information about the most recent contact that is added to the <strong>Information Management</strong> module is used. For more information about how to add a contact to the <strong>Information Management</strong> module, see <a href="https://help.aliyun.com/document_detail/198262.html">Manage contacts</a>.</p>
     * 
     * <strong>example:</strong>
     * <p>Tom</p>
     */
    @NameInMap("Username")
    public String username;

    /**
     * <p>The verification method of the domain name ownership. Valid values:</p>
     * <ul>
     * <li><strong>DNS</strong>: DNS verification. If you use this method, you must add a TXT record to the DNS records of the domain name in the management platform of the domain name. You must have operation permissions on domain name resolution to verify the ownership of the domain name.</li>
     * <li><strong>FILE</strong>: file verification. If you use this method, you must create a specified file on the DNS server. You must have administrative rights on the DNS server to verify the ownership of the domain name.</li>
     * </ul>
     * <p>For more information about the verification methods, see <a href="https://help.aliyun.com/document_detail/48016.html">Verify the ownership of a domain name</a>.</p>
     * 
     * <strong>example:</strong>
     * <p>DNS</p>
     */
    @NameInMap("ValidateType")
    public String validateType;

    public static CreateCertificateForPackageRequestRequest build(java.util.Map<String, ?> map) throws Exception {
        CreateCertificateForPackageRequestRequest self = new CreateCertificateForPackageRequestRequest();
        return TeaModel.build(map, self);
    }

    public CreateCertificateForPackageRequestRequest setCompanyName(String companyName) {
        this.companyName = companyName;
        return this;
    }
    public String getCompanyName() {
        return this.companyName;
    }

    public CreateCertificateForPackageRequestRequest setCsr(String csr) {
        this.csr = csr;
        return this;
    }
    public String getCsr() {
        return this.csr;
    }

    public CreateCertificateForPackageRequestRequest setDomain(String domain) {
        this.domain = domain;
        return this;
    }
    public String getDomain() {
        return this.domain;
    }

    public CreateCertificateForPackageRequestRequest setEmail(String email) {
        this.email = email;
        return this;
    }
    public String getEmail() {
        return this.email;
    }

    public CreateCertificateForPackageRequestRequest setPhone(String phone) {
        this.phone = phone;
        return this;
    }
    public String getPhone() {
        return this.phone;
    }

    public CreateCertificateForPackageRequestRequest setProductCode(String productCode) {
        this.productCode = productCode;
        return this;
    }
    public String getProductCode() {
        return this.productCode;
    }

    public CreateCertificateForPackageRequestRequest setTags(java.util.List<CreateCertificateForPackageRequestRequestTags> tags) {
        this.tags = tags;
        return this;
    }
    public java.util.List<CreateCertificateForPackageRequestRequestTags> getTags() {
        return this.tags;
    }

    public CreateCertificateForPackageRequestRequest setUsername(String username) {
        this.username = username;
        return this;
    }
    public String getUsername() {
        return this.username;
    }

    public CreateCertificateForPackageRequestRequest setValidateType(String validateType) {
        this.validateType = validateType;
        return this;
    }
    public String getValidateType() {
        return this.validateType;
    }

    public static class CreateCertificateForPackageRequestRequestTags extends TeaModel {
        /**
         * <p>The tag key.</p>
         * 
         * <strong>example:</strong>
         * <p>runtime</p>
         */
        @NameInMap("Key")
        public String key;

        /**
         * <p>The tag value.</p>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("Value")
        public String value;

        public static CreateCertificateForPackageRequestRequestTags build(java.util.Map<String, ?> map) throws Exception {
            CreateCertificateForPackageRequestRequestTags self = new CreateCertificateForPackageRequestRequestTags();
            return TeaModel.build(map, self);
        }

        public CreateCertificateForPackageRequestRequestTags setKey(String key) {
            this.key = key;
            return this;
        }
        public String getKey() {
            return this.key;
        }

        public CreateCertificateForPackageRequestRequestTags setValue(String value) {
            this.value = value;
            return this;
        }
        public String getValue() {
            return this.value;
        }

    }

}
