// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.kvcachestore20260617.models;

import com.aliyun.tea.*;

public class DetachKVCacheStoreRequest extends TeaModel {
    /**
     * <p>A string generated by the server that serves as a unique identifier for the client request.</p>
     * 
     * <strong>example:</strong>
     * <p>YOUR_CLIENT_TOKEN</p>
     */
    @NameInMap("ClientToken")
    public String clientToken;

    /**
     * <p>The region ID, such as cn-hangzhou.</p>
     * <p>This parameter is required.</p>
     * 
     * <strong>example:</strong>
     * <p>cn-hangzhou</p>
     */
    @NameInMap("RegionId")
    public String regionId;

    /**
     * <p>The list of resources to unmount. A maximum of 100 resources can be specified.</p>
     * <p>This parameter is required.</p>
     */
    @NameInMap("ResourceIds")
    public java.util.List<DetachKVCacheStoreRequestResourceIds> resourceIds;

    public static DetachKVCacheStoreRequest build(java.util.Map<String, ?> map) throws Exception {
        DetachKVCacheStoreRequest self = new DetachKVCacheStoreRequest();
        return TeaModel.build(map, self);
    }

    public DetachKVCacheStoreRequest setClientToken(String clientToken) {
        this.clientToken = clientToken;
        return this;
    }
    public String getClientToken() {
        return this.clientToken;
    }

    public DetachKVCacheStoreRequest setRegionId(String regionId) {
        this.regionId = regionId;
        return this;
    }
    public String getRegionId() {
        return this.regionId;
    }

    public DetachKVCacheStoreRequest setResourceIds(java.util.List<DetachKVCacheStoreRequestResourceIds> resourceIds) {
        this.resourceIds = resourceIds;
        return this;
    }
    public java.util.List<DetachKVCacheStoreRequestResourceIds> getResourceIds() {
        return this.resourceIds;
    }

    public static class DetachKVCacheStoreRequestResourceIds extends TeaModel {
        /**
         * <p>KVCacheStore KvcsId</p>
         * <p>This parameter is required.</p>
         * 
         * <strong>example:</strong>
         * <p>kvcs-your-resource-id</p>
         */
        @NameInMap("KvcsId")
        public String kvcsId;

        /**
         * <p>The VSC ID on the compute side.</p>
         * <p>This parameter is required.</p>
         * 
         * <strong>example:</strong>
         * <p>vsc-uf6cpove22nrjnpenwkyal</p>
         */
        @NameInMap("VscId")
        public String vscId;

        public static DetachKVCacheStoreRequestResourceIds build(java.util.Map<String, ?> map) throws Exception {
            DetachKVCacheStoreRequestResourceIds self = new DetachKVCacheStoreRequestResourceIds();
            return TeaModel.build(map, self);
        }

        public DetachKVCacheStoreRequestResourceIds setKvcsId(String kvcsId) {
            this.kvcsId = kvcsId;
            return this;
        }
        public String getKvcsId() {
            return this.kvcsId;
        }

        public DetachKVCacheStoreRequestResourceIds setVscId(String vscId) {
            this.vscId = vscId;
            return this;
        }
        public String getVscId() {
            return this.vscId;
        }

    }

}
