// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.green20220302.models;

import com.aliyun.tea.*;

public class ImageModerationResponseBody extends TeaModel {
    /**
     * <p>The return code. A value of 200 indicates that the request was successful.</p>
     * 
     * <strong>example:</strong>
     * <p>200</p>
     */
    @NameInMap("Code")
    public Integer code;

    /**
     * <p>The results of the image content moderation.</p>
     */
    @NameInMap("Data")
    public ImageModerationResponseBodyData data;

    /**
     * <p>The message returned for the request.</p>
     * 
     * <strong>example:</strong>
     * <p>OK</p>
     */
    @NameInMap("Msg")
    public String msg;

    /**
     * <p>The ID of the request. Alibaba Cloud generates a unique ID for each request. You can use the ID to troubleshoot issues.</p>
     * 
     * <strong>example:</strong>
     * <p>6CF2815C-C8C7-4A01-B52E-FF6E24F53492</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    public static ImageModerationResponseBody build(java.util.Map<String, ?> map) throws Exception {
        ImageModerationResponseBody self = new ImageModerationResponseBody();
        return TeaModel.build(map, self);
    }

    public ImageModerationResponseBody setCode(Integer code) {
        this.code = code;
        return this;
    }
    public Integer getCode() {
        return this.code;
    }

    public ImageModerationResponseBody setData(ImageModerationResponseBodyData data) {
        this.data = data;
        return this;
    }
    public ImageModerationResponseBodyData getData() {
        return this.data;
    }

    public ImageModerationResponseBody setMsg(String msg) {
        this.msg = msg;
        return this;
    }
    public String getMsg() {
        return this.msg;
    }

    public ImageModerationResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public static class ImageModerationResponseBodyDataExtAigcDataAIGC extends TeaModel {
        /**
         * <p>The code or name of the service provider, which identifies the content producer.</p>
         * 
         * <strong>example:</strong>
         * <p>001191******M000100Y43</p>
         */
        @NameInMap("ContentProducer")
        public String contentProducer;

        /**
         * <p>The name, ID, or code of the propagation platform. For services that provide AI-generated content, this can be the same as the value of ContentProducer.</p>
         * 
         * <strong>example:</strong>
         * <p>001191******M000100Y43</p>
         */
        @NameInMap("ContentPropagator")
        public String contentPropagator;

        /**
         * <p>Indicates whether the content is generated by artificial intelligence (AI). Valid values:</p>
         * <ul>
         * <li><p>1: The content is generated by AI.</p>
         * </li>
         * <li><p>2: (For distribution platforms only) The content may be generated by AI.</p>
         * </li>
         * <li><p>3: (For distribution platforms only) The content is suspected to be generated by AI.</p>
         * </li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>1</p>
         */
        @NameInMap("Label")
        public String label;

        /**
         * <p>The content production ID. This is a unique ID used on the production platform to trace the source of synthesized content.</p>
         * 
         * <strong>example:</strong>
         * <p>123******456</p>
         */
        @NameInMap("ProduceID")
        public String produceID;

        /**
         * <p>The content propagation ID. This is a unique ID that the propagation platform assigns to the distributed synthetic content.</p>
         * 
         * <strong>example:</strong>
         * <p>123******456</p>
         */
        @NameInMap("PropagateID")
        public String propagateID;

        /**
         * <p>A reserved field.</p>
         * <p>This field can store information that the generative service provider uses for security protection to ensure the integrity of content and identities. A hashing mechanism based on ContentProducer and ProduceID can be used to securely store and verify key information.</p>
         * 
         * <strong>example:</strong>
         * <p>d41d**********427e</p>
         */
        @NameInMap("ReservedCode1")
        public String reservedCode1;

        /**
         * <p>A reserved field.</p>
         * <p>This field can be used by content distribution service providers for security protection to ensure the integrity of content and identities. A hashing mechanism based on ContentProducer and ProduceID can be used to securely store and verify key information.</p>
         * 
         * <strong>example:</strong>
         * <p>d41d**********427e</p>
         */
        @NameInMap("ReservedCode2")
        public String reservedCode2;

        public static ImageModerationResponseBodyDataExtAigcDataAIGC build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtAigcDataAIGC self = new ImageModerationResponseBodyDataExtAigcDataAIGC();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtAigcDataAIGC setContentProducer(String contentProducer) {
            this.contentProducer = contentProducer;
            return this;
        }
        public String getContentProducer() {
            return this.contentProducer;
        }

        public ImageModerationResponseBodyDataExtAigcDataAIGC setContentPropagator(String contentPropagator) {
            this.contentPropagator = contentPropagator;
            return this;
        }
        public String getContentPropagator() {
            return this.contentPropagator;
        }

        public ImageModerationResponseBodyDataExtAigcDataAIGC setLabel(String label) {
            this.label = label;
            return this;
        }
        public String getLabel() {
            return this.label;
        }

        public ImageModerationResponseBodyDataExtAigcDataAIGC setProduceID(String produceID) {
            this.produceID = produceID;
            return this;
        }
        public String getProduceID() {
            return this.produceID;
        }

        public ImageModerationResponseBodyDataExtAigcDataAIGC setPropagateID(String propagateID) {
            this.propagateID = propagateID;
            return this;
        }
        public String getPropagateID() {
            return this.propagateID;
        }

        public ImageModerationResponseBodyDataExtAigcDataAIGC setReservedCode1(String reservedCode1) {
            this.reservedCode1 = reservedCode1;
            return this;
        }
        public String getReservedCode1() {
            return this.reservedCode1;
        }

        public ImageModerationResponseBodyDataExtAigcDataAIGC setReservedCode2(String reservedCode2) {
            this.reservedCode2 = reservedCode2;
            return this;
        }
        public String getReservedCode2() {
            return this.reservedCode2;
        }

    }

    public static class ImageModerationResponseBodyDataExtAigcData extends TeaModel {
        /**
         * <p>The detection information for the implicit AIGC identity.</p>
         */
        @NameInMap("AIGC")
        public ImageModerationResponseBodyDataExtAigcDataAIGC AIGC;

        public static ImageModerationResponseBodyDataExtAigcData build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtAigcData self = new ImageModerationResponseBodyDataExtAigcData();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtAigcData setAIGC(ImageModerationResponseBodyDataExtAigcDataAIGC AIGC) {
            this.AIGC = AIGC;
            return this;
        }
        public ImageModerationResponseBodyDataExtAigcDataAIGC getAIGC() {
            return this.AIGC;
        }

    }

    public static class ImageModerationResponseBodyDataExtCustomImage extends TeaModel {
        /**
         * <p>The ID of the hit custom image.</p>
         * 
         * <strong>example:</strong>
         * <p>123456</p>
         */
        @NameInMap("ImageId")
        public String imageId;

        /**
         * <p>The ID of the hit custom image library.</p>
         * 
         * <strong>example:</strong>
         * <p>图库123</p>
         */
        @NameInMap("LibId")
        public String libId;

        /**
         * <p>The name of the hit custom image library.</p>
         * 
         * <strong>example:</strong>
         * <p>图库123</p>
         */
        @NameInMap("LibName")
        public String libName;

        public static ImageModerationResponseBodyDataExtCustomImage build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtCustomImage self = new ImageModerationResponseBodyDataExtCustomImage();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtCustomImage setImageId(String imageId) {
            this.imageId = imageId;
            return this;
        }
        public String getImageId() {
            return this.imageId;
        }

        public ImageModerationResponseBodyDataExtCustomImage setLibId(String libId) {
            this.libId = libId;
            return this;
        }
        public String getLibId() {
            return this.libId;
        }

        public ImageModerationResponseBodyDataExtCustomImage setLibName(String libName) {
            this.libName = libName;
            return this;
        }
        public String getLibName() {
            return this.libName;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceDataBang extends TeaModel {
        /**
         * <p>The confidence level of the bangs detection. The value ranges from 0 to 100. A higher value indicates a more reliable result.</p>
         * 
         * <strong>example:</strong>
         * <p>81.88</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        /**
         * <p>The detection result for bangs. Valid values:</p>
         * <ul>
         * <li><p>Has: The person has bangs.</p>
         * </li>
         * <li><p>None: The person does not have bangs.</p>
         * </li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>Has</p>
         */
        @NameInMap("Value")
        public String value;

        public static ImageModerationResponseBodyDataExtFaceDataBang build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceDataBang self = new ImageModerationResponseBodyDataExtFaceDataBang();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceDataBang setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

        public ImageModerationResponseBodyDataExtFaceDataBang setValue(String value) {
            this.value = value;
            return this;
        }
        public String getValue() {
            return this.value;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceDataGender extends TeaModel {
        /**
         * <p>The confidence level of the gender detection. The value ranges from 0 to 100. A higher value indicates a more reliable result.</p>
         * 
         * <strong>example:</strong>
         * <p>81.88</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        /**
         * <p>The detected gender. Valid values:</p>
         * <ul>
         * <li><p>Male: male</p>
         * </li>
         * <li><p>FeMale: female</p>
         * </li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>FeMale</p>
         */
        @NameInMap("Value")
        public String value;

        public static ImageModerationResponseBodyDataExtFaceDataGender build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceDataGender self = new ImageModerationResponseBodyDataExtFaceDataGender();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceDataGender setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

        public ImageModerationResponseBodyDataExtFaceDataGender setValue(String value) {
            this.value = value;
            return this;
        }
        public String getValue() {
            return this.value;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceDataHairstyle extends TeaModel {
        /**
         * <p>The confidence level of the hairstyle detection. The value ranges from 0 to 100. A higher value indicates a more reliable result.</p>
         * 
         * <strong>example:</strong>
         * <p>81.88</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        /**
         * <p>The detected hairstyle. Valid values:</p>
         * <ul>
         * <li><p>Bald: bald</p>
         * </li>
         * <li><p>Long: long hair</p>
         * </li>
         * <li><p>Short: short hair</p>
         * </li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>Short</p>
         */
        @NameInMap("Value")
        public String value;

        public static ImageModerationResponseBodyDataExtFaceDataHairstyle build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceDataHairstyle self = new ImageModerationResponseBodyDataExtFaceDataHairstyle();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceDataHairstyle setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

        public ImageModerationResponseBodyDataExtFaceDataHairstyle setValue(String value) {
            this.value = value;
            return this;
        }
        public String getValue() {
            return this.value;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceDataHat extends TeaModel {
        /**
         * <p>The confidence level of the hat detection. The value ranges from 0 to 100. A higher value indicates a more reliable result.</p>
         * 
         * <strong>example:</strong>
         * <p>88.88</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        /**
         * <p>Indicates whether a hat is detected. Valid values:</p>
         * <ul>
         * <li><p>Wear: A hat is worn.</p>
         * </li>
         * <li><p>None: No hat is worn.</p>
         * </li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>Wear</p>
         */
        @NameInMap("Value")
        public String value;

        public static ImageModerationResponseBodyDataExtFaceDataHat build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceDataHat self = new ImageModerationResponseBodyDataExtFaceDataHat();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceDataHat setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

        public ImageModerationResponseBodyDataExtFaceDataHat setValue(String value) {
            this.value = value;
            return this;
        }
        public String getValue() {
            return this.value;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceDataLocation extends TeaModel {
        /**
         * <p>The height of the face area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>26</p>
         */
        @NameInMap("H")
        public Integer h;

        /**
         * <p>The width of the face area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>83</p>
         */
        @NameInMap("W")
        public Integer w;

        /**
         * <p>The distance from the upper-left corner of the face area to the y-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>41</p>
         */
        @NameInMap("X")
        public Integer x;

        /**
         * <p>The distance from the upper-left corner of the face area to the x-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>84</p>
         */
        @NameInMap("Y")
        public Integer y;

        public static ImageModerationResponseBodyDataExtFaceDataLocation build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceDataLocation self = new ImageModerationResponseBodyDataExtFaceDataLocation();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceDataLocation setH(Integer h) {
            this.h = h;
            return this;
        }
        public Integer getH() {
            return this.h;
        }

        public ImageModerationResponseBodyDataExtFaceDataLocation setW(Integer w) {
            this.w = w;
            return this;
        }
        public Integer getW() {
            return this.w;
        }

        public ImageModerationResponseBodyDataExtFaceDataLocation setX(Integer x) {
            this.x = x;
            return this;
        }
        public Integer getX() {
            return this.x;
        }

        public ImageModerationResponseBodyDataExtFaceDataLocation setY(Integer y) {
            this.y = y;
            return this;
        }
        public Integer getY() {
            return this.y;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceDataMask extends TeaModel {
        /**
         * <p>The confidence level of the mask detection. The value ranges from 0 to 100. A higher value indicates a more reliable result.</p>
         * 
         * <strong>example:</strong>
         * <p>99.99</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        /**
         * <p>Indicates whether a mask is worn. Valid values:</p>
         * <ul>
         * <li><p>Wear: A mask is worn.</p>
         * </li>
         * <li><p>None: No mask is worn.</p>
         * </li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>Wear</p>
         */
        @NameInMap("Value")
        public String value;

        public static ImageModerationResponseBodyDataExtFaceDataMask build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceDataMask self = new ImageModerationResponseBodyDataExtFaceDataMask();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceDataMask setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

        public ImageModerationResponseBodyDataExtFaceDataMask setValue(String value) {
            this.value = value;
            return this;
        }
        public String getValue() {
            return this.value;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceDataMustache extends TeaModel {
        /**
         * <p>The confidence level of the mustache detection. The value ranges from 0 to 100. A higher value indicates a more reliable result.</p>
         * 
         * <strong>example:</strong>
         * <p>99.99</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        /**
         * <p>Indicates whether a mustache is present. Valid values:</p>
         * <ul>
         * <li><p>Has: A mustache is present.</p>
         * </li>
         * <li><p>None: No mustache is present.</p>
         * </li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>Has</p>
         */
        @NameInMap("Value")
        public String value;

        public static ImageModerationResponseBodyDataExtFaceDataMustache build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceDataMustache self = new ImageModerationResponseBodyDataExtFaceDataMustache();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceDataMustache setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

        public ImageModerationResponseBodyDataExtFaceDataMustache setValue(String value) {
            this.value = value;
            return this;
        }
        public String getValue() {
            return this.value;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceDataQuality extends TeaModel {
        /**
         * <p>The blurriness of the face image. The value ranges from 0 to 100. A higher score indicates a blurrier image.</p>
         * <p>A value from 0 to 25 is recommended.</p>
         * 
         * <strong>example:</strong>
         * <p>5.88</p>
         */
        @NameInMap("Blur")
        public Float blur;

        /**
         * <p>The integrity of the face. The value ranges from 0 to 100. A higher score indicates a more complete face.</p>
         * <p>A value from 80 to 100 is recommended.</p>
         * 
         * <strong>example:</strong>
         * <p>100.0</p>
         */
        @NameInMap("Integrity")
        public Float integrity;

        /**
         * <p>The pitch angle of the face.</p>
         * <p>A value from -30 to 30 is recommended.</p>
         * 
         * <strong>example:</strong>
         * <p>5.88</p>
         */
        @NameInMap("Pitch")
        public Float pitch;

        /**
         * <p>The roll angle of the face.</p>
         * <p>A value from -30 to 30 is recommended.</p>
         * 
         * <strong>example:</strong>
         * <p>5.18</p>
         */
        @NameInMap("Roll")
        public Float roll;

        /**
         * <p>The yaw angle of the face.</p>
         * <p>A value from -30 to 30 is recommended.</p>
         * 
         * <strong>example:</strong>
         * <p>5.18</p>
         */
        @NameInMap("Yaw")
        public Float yaw;

        public static ImageModerationResponseBodyDataExtFaceDataQuality build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceDataQuality self = new ImageModerationResponseBodyDataExtFaceDataQuality();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceDataQuality setBlur(Float blur) {
            this.blur = blur;
            return this;
        }
        public Float getBlur() {
            return this.blur;
        }

        public ImageModerationResponseBodyDataExtFaceDataQuality setIntegrity(Float integrity) {
            this.integrity = integrity;
            return this;
        }
        public Float getIntegrity() {
            return this.integrity;
        }

        public ImageModerationResponseBodyDataExtFaceDataQuality setPitch(Float pitch) {
            this.pitch = pitch;
            return this;
        }
        public Float getPitch() {
            return this.pitch;
        }

        public ImageModerationResponseBodyDataExtFaceDataQuality setRoll(Float roll) {
            this.roll = roll;
            return this;
        }
        public Float getRoll() {
            return this.roll;
        }

        public ImageModerationResponseBodyDataExtFaceDataQuality setYaw(Float yaw) {
            this.yaw = yaw;
            return this;
        }
        public Float getYaw() {
            return this.yaw;
        }

    }

    public static class ImageModerationResponseBodyDataExtFaceData extends TeaModel {
        /**
         * <p>The detected age.</p>
         * 
         * <strong>example:</strong>
         * <p>18</p>
         */
        @NameInMap("Age")
        public Integer age;

        /**
         * <p>The detection result for bangs.</p>
         */
        @NameInMap("Bang")
        public ImageModerationResponseBodyDataExtFaceDataBang bang;

        /**
         * <p>The gender detection result.</p>
         */
        @NameInMap("Gender")
        public ImageModerationResponseBodyDataExtFaceDataGender gender;

        /**
         * <p>Indicates whether the person is wearing glasses. Valid values:</p>
         * <ul>
         * <li><p>None: The person is not wearing glasses.</p>
         * </li>
         * <li><p>Common: The person is wearing regular glasses.</p>
         * </li>
         * <li><p>Sunglass: The person is wearing sunglasses.</p>
         * </li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>Common</p>
         */
        @NameInMap("Glasses")
        public String glasses;

        /**
         * <p>The hairstyle detection result.</p>
         */
        @NameInMap("Hairstyle")
        public ImageModerationResponseBodyDataExtFaceDataHairstyle hairstyle;

        /**
         * <p>The result of hat detection.</p>
         */
        @NameInMap("Hat")
        public ImageModerationResponseBodyDataExtFaceDataHat hat;

        /**
         * <p>The location of the face.</p>
         */
        @NameInMap("Location")
        public ImageModerationResponseBodyDataExtFaceDataLocation location;

        /**
         * <p>The result of mask detection.</p>
         */
        @NameInMap("Mask")
        public ImageModerationResponseBodyDataExtFaceDataMask mask;

        /**
         * <p>The result of mustache detection.</p>
         */
        @NameInMap("Mustache")
        public ImageModerationResponseBodyDataExtFaceDataMustache mustache;

        /**
         * <p>The quality of the face image.</p>
         */
        @NameInMap("Quality")
        public ImageModerationResponseBodyDataExtFaceDataQuality quality;

        /**
         * <p>The degree of the smile. The value ranges from 0 to 100. A higher score indicates a wider smile.</p>
         * 
         * <strong>example:</strong>
         * <p>85.88</p>
         */
        @NameInMap("Smile")
        public Float smile;

        public static ImageModerationResponseBodyDataExtFaceData build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtFaceData self = new ImageModerationResponseBodyDataExtFaceData();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtFaceData setAge(Integer age) {
            this.age = age;
            return this;
        }
        public Integer getAge() {
            return this.age;
        }

        public ImageModerationResponseBodyDataExtFaceData setBang(ImageModerationResponseBodyDataExtFaceDataBang bang) {
            this.bang = bang;
            return this;
        }
        public ImageModerationResponseBodyDataExtFaceDataBang getBang() {
            return this.bang;
        }

        public ImageModerationResponseBodyDataExtFaceData setGender(ImageModerationResponseBodyDataExtFaceDataGender gender) {
            this.gender = gender;
            return this;
        }
        public ImageModerationResponseBodyDataExtFaceDataGender getGender() {
            return this.gender;
        }

        public ImageModerationResponseBodyDataExtFaceData setGlasses(String glasses) {
            this.glasses = glasses;
            return this;
        }
        public String getGlasses() {
            return this.glasses;
        }

        public ImageModerationResponseBodyDataExtFaceData setHairstyle(ImageModerationResponseBodyDataExtFaceDataHairstyle hairstyle) {
            this.hairstyle = hairstyle;
            return this;
        }
        public ImageModerationResponseBodyDataExtFaceDataHairstyle getHairstyle() {
            return this.hairstyle;
        }

        public ImageModerationResponseBodyDataExtFaceData setHat(ImageModerationResponseBodyDataExtFaceDataHat hat) {
            this.hat = hat;
            return this;
        }
        public ImageModerationResponseBodyDataExtFaceDataHat getHat() {
            return this.hat;
        }

        public ImageModerationResponseBodyDataExtFaceData setLocation(ImageModerationResponseBodyDataExtFaceDataLocation location) {
            this.location = location;
            return this;
        }
        public ImageModerationResponseBodyDataExtFaceDataLocation getLocation() {
            return this.location;
        }

        public ImageModerationResponseBodyDataExtFaceData setMask(ImageModerationResponseBodyDataExtFaceDataMask mask) {
            this.mask = mask;
            return this;
        }
        public ImageModerationResponseBodyDataExtFaceDataMask getMask() {
            return this.mask;
        }

        public ImageModerationResponseBodyDataExtFaceData setMustache(ImageModerationResponseBodyDataExtFaceDataMustache mustache) {
            this.mustache = mustache;
            return this;
        }
        public ImageModerationResponseBodyDataExtFaceDataMustache getMustache() {
            return this.mustache;
        }

        public ImageModerationResponseBodyDataExtFaceData setQuality(ImageModerationResponseBodyDataExtFaceDataQuality quality) {
            this.quality = quality;
            return this;
        }
        public ImageModerationResponseBodyDataExtFaceDataQuality getQuality() {
            return this.quality;
        }

        public ImageModerationResponseBodyDataExtFaceData setSmile(Float smile) {
            this.smile = smile;
            return this;
        }
        public Float getSmile() {
            return this.smile;
        }

    }

    public static class ImageModerationResponseBodyDataExtLogoDataLocation extends TeaModel {
        /**
         * <p>The height of the detected area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>440</p>
         */
        @NameInMap("H")
        public Integer h;

        /**
         * <p>The width of the detected area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>330</p>
         */
        @NameInMap("W")
        public Integer w;

        /**
         * <p>The distance from the upper-left corner of the detected area to the y-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>11</p>
         */
        @NameInMap("X")
        public Integer x;

        /**
         * <p>The distance from the upper-left corner of the detected area to the x-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>22</p>
         */
        @NameInMap("Y")
        public Integer y;

        public static ImageModerationResponseBodyDataExtLogoDataLocation build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtLogoDataLocation self = new ImageModerationResponseBodyDataExtLogoDataLocation();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtLogoDataLocation setH(Integer h) {
            this.h = h;
            return this;
        }
        public Integer getH() {
            return this.h;
        }

        public ImageModerationResponseBodyDataExtLogoDataLocation setW(Integer w) {
            this.w = w;
            return this;
        }
        public Integer getW() {
            return this.w;
        }

        public ImageModerationResponseBodyDataExtLogoDataLocation setX(Integer x) {
            this.x = x;
            return this;
        }
        public Integer getX() {
            return this.x;
        }

        public ImageModerationResponseBodyDataExtLogoDataLocation setY(Integer y) {
            this.y = y;
            return this;
        }
        public Integer getY() {
            return this.y;
        }

    }

    public static class ImageModerationResponseBodyDataExtLogoDataLogo extends TeaModel {
        /**
         * <p>The confidence score. The value ranges from 0 to 100, with two decimal places retained.</p>
         * 
         * <strong>example:</strong>
         * <p>99.1</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        /**
         * <p>The identity category.</p>
         * 
         * <strong>example:</strong>
         * <p>logo_sns</p>
         */
        @NameInMap("Label")
        public String label;

        /**
         * <p>The identity name.</p>
         * 
         * <strong>example:</strong>
         * <p>钉钉</p>
         */
        @NameInMap("Name")
        public String name;

        public static ImageModerationResponseBodyDataExtLogoDataLogo build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtLogoDataLogo self = new ImageModerationResponseBodyDataExtLogoDataLogo();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtLogoDataLogo setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

        public ImageModerationResponseBodyDataExtLogoDataLogo setLabel(String label) {
            this.label = label;
            return this;
        }
        public String getLabel() {
            return this.label;
        }

        public ImageModerationResponseBodyDataExtLogoDataLogo setName(String name) {
            this.name = name;
            return this;
        }
        public String getName() {
            return this.name;
        }

    }

    public static class ImageModerationResponseBodyDataExtLogoData extends TeaModel {
        /**
         * <p>The location of the logo.</p>
         */
        @NameInMap("Location")
        public ImageModerationResponseBodyDataExtLogoDataLocation location;

        /**
         * <p>The identity information.</p>
         */
        @NameInMap("Logo")
        public java.util.List<ImageModerationResponseBodyDataExtLogoDataLogo> logo;

        public static ImageModerationResponseBodyDataExtLogoData build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtLogoData self = new ImageModerationResponseBodyDataExtLogoData();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtLogoData setLocation(ImageModerationResponseBodyDataExtLogoDataLocation location) {
            this.location = location;
            return this;
        }
        public ImageModerationResponseBodyDataExtLogoDataLocation getLocation() {
            return this.location;
        }

        public ImageModerationResponseBodyDataExtLogoData setLogo(java.util.List<ImageModerationResponseBodyDataExtLogoDataLogo> logo) {
            this.logo = logo;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtLogoDataLogo> getLogo() {
            return this.logo;
        }

    }

    public static class ImageModerationResponseBodyDataExtOcrResultLocation extends TeaModel {
        /**
         * <p>The height of the text area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>44</p>
         */
        @NameInMap("H")
        public Integer h;

        /**
         * <p>The width of the text area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>33</p>
         */
        @NameInMap("W")
        public Integer w;

        /**
         * <p>The distance from the upper-left corner of the text area to the y-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>11</p>
         */
        @NameInMap("X")
        public Integer x;

        /**
         * <p>The distance from the upper-left corner of the text area to the x-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>22</p>
         */
        @NameInMap("Y")
        public Integer y;

        public static ImageModerationResponseBodyDataExtOcrResultLocation build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtOcrResultLocation self = new ImageModerationResponseBodyDataExtOcrResultLocation();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtOcrResultLocation setH(Integer h) {
            this.h = h;
            return this;
        }
        public Integer getH() {
            return this.h;
        }

        public ImageModerationResponseBodyDataExtOcrResultLocation setW(Integer w) {
            this.w = w;
            return this;
        }
        public Integer getW() {
            return this.w;
        }

        public ImageModerationResponseBodyDataExtOcrResultLocation setX(Integer x) {
            this.x = x;
            return this;
        }
        public Integer getX() {
            return this.x;
        }

        public ImageModerationResponseBodyDataExtOcrResultLocation setY(Integer y) {
            this.y = y;
            return this;
        }
        public Integer getY() {
            return this.y;
        }

    }

    public static class ImageModerationResponseBodyDataExtOcrResult extends TeaModel {
        /**
         * <p>The coordinates of the text line.</p>
         */
        @NameInMap("Location")
        public ImageModerationResponseBodyDataExtOcrResultLocation location;

        /**
         * <p>A single line of recognized text.</p>
         * 
         * <strong>example:</strong>
         * <p>abcd</p>
         */
        @NameInMap("Text")
        public String text;

        public static ImageModerationResponseBodyDataExtOcrResult build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtOcrResult self = new ImageModerationResponseBodyDataExtOcrResult();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtOcrResult setLocation(ImageModerationResponseBodyDataExtOcrResultLocation location) {
            this.location = location;
            return this;
        }
        public ImageModerationResponseBodyDataExtOcrResultLocation getLocation() {
            return this.location;
        }

        public ImageModerationResponseBodyDataExtOcrResult setText(String text) {
            this.text = text;
            return this;
        }
        public String getText() {
            return this.text;
        }

    }

    public static class ImageModerationResponseBodyDataExtPublicFigureLocation extends TeaModel {
        /**
         * <p>The height of the detected area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>440</p>
         */
        @NameInMap("H")
        public Integer h;

        /**
         * <p>The width of the detected area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>330</p>
         */
        @NameInMap("W")
        public Integer w;

        /**
         * <p>The distance from the upper-left corner of the detected area to the y-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>11</p>
         */
        @NameInMap("X")
        public Integer x;

        /**
         * <p>The distance from the upper-left corner of the detected area to the x-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>22</p>
         */
        @NameInMap("Y")
        public Integer y;

        public static ImageModerationResponseBodyDataExtPublicFigureLocation build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtPublicFigureLocation self = new ImageModerationResponseBodyDataExtPublicFigureLocation();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtPublicFigureLocation setH(Integer h) {
            this.h = h;
            return this;
        }
        public Integer getH() {
            return this.h;
        }

        public ImageModerationResponseBodyDataExtPublicFigureLocation setW(Integer w) {
            this.w = w;
            return this;
        }
        public Integer getW() {
            return this.w;
        }

        public ImageModerationResponseBodyDataExtPublicFigureLocation setX(Integer x) {
            this.x = x;
            return this;
        }
        public Integer getX() {
            return this.x;
        }

        public ImageModerationResponseBodyDataExtPublicFigureLocation setY(Integer y) {
            this.y = y;
            return this;
        }
        public Integer getY() {
            return this.y;
        }

    }

    public static class ImageModerationResponseBodyDataExtPublicFigure extends TeaModel {
        /**
         * <p>The ID of the detected public figure.</p>
         * 
         * <strong>example:</strong>
         * <p>xxx001</p>
         */
        @NameInMap("FigureId")
        public String figureId;

        /**
         * <p>The name of the detected public figure.</p>
         * 
         * <strong>example:</strong>
         * <p>yzazhzou</p>
         */
        @NameInMap("FigureName")
        public String figureName;

        /**
         * <p>The location of the identity.</p>
         */
        @NameInMap("Location")
        public java.util.List<ImageModerationResponseBodyDataExtPublicFigureLocation> location;

        public static ImageModerationResponseBodyDataExtPublicFigure build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtPublicFigure self = new ImageModerationResponseBodyDataExtPublicFigure();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtPublicFigure setFigureId(String figureId) {
            this.figureId = figureId;
            return this;
        }
        public String getFigureId() {
            return this.figureId;
        }

        public ImageModerationResponseBodyDataExtPublicFigure setFigureName(String figureName) {
            this.figureName = figureName;
            return this;
        }
        public String getFigureName() {
            return this.figureName;
        }

        public ImageModerationResponseBodyDataExtPublicFigure setLocation(java.util.List<ImageModerationResponseBodyDataExtPublicFigureLocation> location) {
            this.location = location;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtPublicFigureLocation> getLocation() {
            return this.location;
        }

    }

    public static class ImageModerationResponseBodyDataExtRecognition extends TeaModel {
        /**
         * <p>The category of the recognized object in the image.</p>
         * 
         * <strong>example:</strong>
         * <p>办公大楼</p>
         */
        @NameInMap("Classification")
        public String classification;

        /**
         * <p>The confidence level. The value ranges from 0 to 100, with two decimal places retained. No confidence level is returned when the value is nonLabel.</p>
         * 
         * <strong>example:</strong>
         * <p>81.22</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        public static ImageModerationResponseBodyDataExtRecognition build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtRecognition self = new ImageModerationResponseBodyDataExtRecognition();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtRecognition setClassification(String classification) {
            this.classification = classification;
            return this;
        }
        public String getClassification() {
            return this.classification;
        }

        public ImageModerationResponseBodyDataExtRecognition setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

    }

    public static class ImageModerationResponseBodyDataExtTextInImageCustomText extends TeaModel {
        /**
         * <p>The custom words. Separate multiple words with commas.</p>
         * 
         * <strong>example:</strong>
         * <p>自定义词1,自定义词2</p>
         */
        @NameInMap("KeyWords")
        public String keyWords;

        /**
         * <p>The custom library ID.</p>
         * 
         * <strong>example:</strong>
         * <p>123456</p>
         */
        @NameInMap("LibId")
        public String libId;

        /**
         * <p>The name of the custom library.</p>
         * 
         * <strong>example:</strong>
         * <p>自定义库1</p>
         */
        @NameInMap("LibName")
        public String libName;

        public static ImageModerationResponseBodyDataExtTextInImageCustomText build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtTextInImageCustomText self = new ImageModerationResponseBodyDataExtTextInImageCustomText();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtTextInImageCustomText setKeyWords(String keyWords) {
            this.keyWords = keyWords;
            return this;
        }
        public String getKeyWords() {
            return this.keyWords;
        }

        public ImageModerationResponseBodyDataExtTextInImageCustomText setLibId(String libId) {
            this.libId = libId;
            return this;
        }
        public String getLibId() {
            return this.libId;
        }

        public ImageModerationResponseBodyDataExtTextInImageCustomText setLibName(String libName) {
            this.libName = libName;
            return this;
        }
        public String getLibName() {
            return this.libName;
        }

    }

    public static class ImageModerationResponseBodyDataExtTextInImageOcrResultLocation extends TeaModel {
        /**
         * <p>The height of the text area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>33</p>
         */
        @NameInMap("H")
        public Integer h;

        /**
         * <p>The width of the text area. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>44</p>
         */
        @NameInMap("W")
        public Integer w;

        /**
         * <p>The distance from the upper-left corner of the text area to the y-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>11</p>
         */
        @NameInMap("X")
        public Integer x;

        /**
         * <p>The distance from the upper-left corner of the text area to the x-axis. The origin is the upper-left corner of the image. Unit: pixel.</p>
         * 
         * <strong>example:</strong>
         * <p>22</p>
         */
        @NameInMap("Y")
        public Integer y;

        public static ImageModerationResponseBodyDataExtTextInImageOcrResultLocation build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtTextInImageOcrResultLocation self = new ImageModerationResponseBodyDataExtTextInImageOcrResultLocation();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtTextInImageOcrResultLocation setH(Integer h) {
            this.h = h;
            return this;
        }
        public Integer getH() {
            return this.h;
        }

        public ImageModerationResponseBodyDataExtTextInImageOcrResultLocation setW(Integer w) {
            this.w = w;
            return this;
        }
        public Integer getW() {
            return this.w;
        }

        public ImageModerationResponseBodyDataExtTextInImageOcrResultLocation setX(Integer x) {
            this.x = x;
            return this;
        }
        public Integer getX() {
            return this.x;
        }

        public ImageModerationResponseBodyDataExtTextInImageOcrResultLocation setY(Integer y) {
            this.y = y;
            return this;
        }
        public Integer getY() {
            return this.y;
        }

    }

    public static class ImageModerationResponseBodyDataExtTextInImageOcrResult extends TeaModel {
        /**
         * <p>The coordinates of the text line.</p>
         */
        @NameInMap("Location")
        public ImageModerationResponseBodyDataExtTextInImageOcrResultLocation location;

        /**
         * <p>The text.</p>
         * 
         * <strong>example:</strong>
         * <p>abcd</p>
         */
        @NameInMap("Text")
        public String text;

        public static ImageModerationResponseBodyDataExtTextInImageOcrResult build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtTextInImageOcrResult self = new ImageModerationResponseBodyDataExtTextInImageOcrResult();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtTextInImageOcrResult setLocation(ImageModerationResponseBodyDataExtTextInImageOcrResultLocation location) {
            this.location = location;
            return this;
        }
        public ImageModerationResponseBodyDataExtTextInImageOcrResultLocation getLocation() {
            return this.location;
        }

        public ImageModerationResponseBodyDataExtTextInImageOcrResult setText(String text) {
            this.text = text;
            return this;
        }
        public String getText() {
            return this.text;
        }

    }

    public static class ImageModerationResponseBodyDataExtTextInImage extends TeaModel {
        /**
         * <p>If a custom text library is hit, the custom library ID, custom library name, and custom word are returned.</p>
         */
        @NameInMap("CustomText")
        public java.util.List<ImageModerationResponseBodyDataExtTextInImageCustomText> customText;

        /**
         * <p>Each line of text recognized in the image.</p>
         */
        @NameInMap("OcrResult")
        public java.util.List<ImageModerationResponseBodyDataExtTextInImageOcrResult> ocrResult;

        /**
         * <p>The hit threat keywords.</p>
         */
        @NameInMap("RiskWord")
        public java.util.List<String> riskWord;

        public static ImageModerationResponseBodyDataExtTextInImage build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtTextInImage self = new ImageModerationResponseBodyDataExtTextInImage();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtTextInImage setCustomText(java.util.List<ImageModerationResponseBodyDataExtTextInImageCustomText> customText) {
            this.customText = customText;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtTextInImageCustomText> getCustomText() {
            return this.customText;
        }

        public ImageModerationResponseBodyDataExtTextInImage setOcrResult(java.util.List<ImageModerationResponseBodyDataExtTextInImageOcrResult> ocrResult) {
            this.ocrResult = ocrResult;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtTextInImageOcrResult> getOcrResult() {
            return this.ocrResult;
        }

        public ImageModerationResponseBodyDataExtTextInImage setRiskWord(java.util.List<String> riskWord) {
            this.riskWord = riskWord;
            return this;
        }
        public java.util.List<String> getRiskWord() {
            return this.riskWord;
        }

    }

    public static class ImageModerationResponseBodyDataExtVlContent extends TeaModel {
        /**
         * <p>The output content.</p>
         * 
         * <strong>example:</strong>
         * <p>这是一段描述</p>
         */
        @NameInMap("OutputText")
        public String outputText;

        public static ImageModerationResponseBodyDataExtVlContent build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExtVlContent self = new ImageModerationResponseBodyDataExtVlContent();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExtVlContent setOutputText(String outputText) {
            this.outputText = outputText;
            return this;
        }
        public String getOutputText() {
            return this.outputText;
        }

    }

    public static class ImageModerationResponseBodyDataExt extends TeaModel {
        /**
         * <p>The detection information for the implicit AIGC identity in the image.</p>
         */
        @NameInMap("AigcData")
        public ImageModerationResponseBodyDataExtAigcData aigcData;

        /**
         * <p>A list of hits from the custom image library.</p>
         */
        @NameInMap("CustomImage")
        public java.util.List<ImageModerationResponseBodyDataExtCustomImage> customImage;

        /**
         * <p>The facial attribute detection results.</p>
         */
        @NameInMap("FaceData")
        public java.util.List<ImageModerationResponseBodyDataExtFaceData> faceData;

        /**
         * <p>The identity information.</p>
         */
        @NameInMap("LogoData")
        public java.util.List<ImageModerationResponseBodyDataExtLogoData> logoData;

        /**
         * <p>The results of optical character recognition (OCR).</p>
         */
        @NameInMap("OcrResult")
        public java.util.List<ImageModerationResponseBodyDataExtOcrResult> ocrResult;

        /**
         * <p>A list of public figures.</p>
         */
        @NameInMap("PublicFigure")
        public java.util.List<ImageModerationResponseBodyDataExtPublicFigure> publicFigure;

        /**
         * <p>The results of image object recognition.</p>
         */
        @NameInMap("Recognition")
        public java.util.List<ImageModerationResponseBodyDataExtRecognition> recognition;

        /**
         * <p>The text information that is hit in the image.</p>
         */
        @NameInMap("TextInImage")
        public ImageModerationResponseBodyDataExtTextInImage textInImage;

        /**
         * <p>The output content.</p>
         */
        @NameInMap("VlContent")
        public ImageModerationResponseBodyDataExtVlContent vlContent;

        public static ImageModerationResponseBodyDataExt build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataExt self = new ImageModerationResponseBodyDataExt();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataExt setAigcData(ImageModerationResponseBodyDataExtAigcData aigcData) {
            this.aigcData = aigcData;
            return this;
        }
        public ImageModerationResponseBodyDataExtAigcData getAigcData() {
            return this.aigcData;
        }

        public ImageModerationResponseBodyDataExt setCustomImage(java.util.List<ImageModerationResponseBodyDataExtCustomImage> customImage) {
            this.customImage = customImage;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtCustomImage> getCustomImage() {
            return this.customImage;
        }

        public ImageModerationResponseBodyDataExt setFaceData(java.util.List<ImageModerationResponseBodyDataExtFaceData> faceData) {
            this.faceData = faceData;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtFaceData> getFaceData() {
            return this.faceData;
        }

        public ImageModerationResponseBodyDataExt setLogoData(java.util.List<ImageModerationResponseBodyDataExtLogoData> logoData) {
            this.logoData = logoData;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtLogoData> getLogoData() {
            return this.logoData;
        }

        public ImageModerationResponseBodyDataExt setOcrResult(java.util.List<ImageModerationResponseBodyDataExtOcrResult> ocrResult) {
            this.ocrResult = ocrResult;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtOcrResult> getOcrResult() {
            return this.ocrResult;
        }

        public ImageModerationResponseBodyDataExt setPublicFigure(java.util.List<ImageModerationResponseBodyDataExtPublicFigure> publicFigure) {
            this.publicFigure = publicFigure;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtPublicFigure> getPublicFigure() {
            return this.publicFigure;
        }

        public ImageModerationResponseBodyDataExt setRecognition(java.util.List<ImageModerationResponseBodyDataExtRecognition> recognition) {
            this.recognition = recognition;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataExtRecognition> getRecognition() {
            return this.recognition;
        }

        public ImageModerationResponseBodyDataExt setTextInImage(ImageModerationResponseBodyDataExtTextInImage textInImage) {
            this.textInImage = textInImage;
            return this;
        }
        public ImageModerationResponseBodyDataExtTextInImage getTextInImage() {
            return this.textInImage;
        }

        public ImageModerationResponseBodyDataExt setVlContent(ImageModerationResponseBodyDataExtVlContent vlContent) {
            this.vlContent = vlContent;
            return this;
        }
        public ImageModerationResponseBodyDataExtVlContent getVlContent() {
            return this.vlContent;
        }

    }

    public static class ImageModerationResponseBodyDataResult extends TeaModel {
        /**
         * <p>The confidence level. The value ranges from 0 to 100, with two decimal places retained. Some labels do not have a confidence level.</p>
         * 
         * <strong>example:</strong>
         * <p>81.22</p>
         */
        @NameInMap("Confidence")
        public Float confidence;

        /**
         * <p>The description.</p>
         * 
         * <strong>example:</strong>
         * <p>未检测出风险</p>
         */
        @NameInMap("Description")
        public String description;

        /**
         * <p>The label returned after the image content is moderated. Multiple labels and scores may be returned for a single image.</p>
         * 
         * <strong>example:</strong>
         * <p>violent_explosion</p>
         */
        @NameInMap("Label")
        public String label;

        /**
         * <p>The threat level.</p>
         * 
         * <strong>example:</strong>
         * <p>high</p>
         */
        @NameInMap("RiskLevel")
        public String riskLevel;

        public static ImageModerationResponseBodyDataResult build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyDataResult self = new ImageModerationResponseBodyDataResult();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyDataResult setConfidence(Float confidence) {
            this.confidence = confidence;
            return this;
        }
        public Float getConfidence() {
            return this.confidence;
        }

        public ImageModerationResponseBodyDataResult setDescription(String description) {
            this.description = description;
            return this;
        }
        public String getDescription() {
            return this.description;
        }

        public ImageModerationResponseBodyDataResult setLabel(String label) {
            this.label = label;
            return this;
        }
        public String getLabel() {
            return this.label;
        }

        public ImageModerationResponseBodyDataResult setRiskLevel(String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }
        public String getRiskLevel() {
            return this.riskLevel;
        }

    }

    public static class ImageModerationResponseBodyData extends TeaModel {
        /**
         * <p>The AccountId specified in the request.</p>
         * 
         * <strong>example:</strong>
         * <p>testaccountid123</p>
         */
        @NameInMap("AccountId")
        public String accountId;

        /**
         * <p>The data ID of the detected object.</p>
         * <blockquote>
         * <p>If you specify the dataId parameter in the request, the corresponding dataId is returned.</p>
         * </blockquote>
         * 
         * <strong>example:</strong>
         * <p>fb5ffab1-993b-449f-b8d6-b97d5e3331f2</p>
         */
        @NameInMap("DataId")
        public String dataId;

        /**
         * <p>Auxiliary reference information for the image.</p>
         */
        @NameInMap("Ext")
        public ImageModerationResponseBodyDataExt ext;

        /**
         * <p>The ID of the manual review task.</p>
         * 
         * <strong>example:</strong>
         * <p>xxxxx-xxxxx</p>
         */
        @NameInMap("ManualTaskId")
        public String manualTaskId;

        /**
         * <p>The results of the image moderation, including the threat labels and confidence levels. The value is an array.</p>
         */
        @NameInMap("Result")
        public java.util.List<ImageModerationResponseBodyDataResult> result;

        /**
         * <p>The threat level.</p>
         * 
         * <strong>example:</strong>
         * <p>high</p>
         */
        @NameInMap("RiskLevel")
        public String riskLevel;

        public static ImageModerationResponseBodyData build(java.util.Map<String, ?> map) throws Exception {
            ImageModerationResponseBodyData self = new ImageModerationResponseBodyData();
            return TeaModel.build(map, self);
        }

        public ImageModerationResponseBodyData setAccountId(String accountId) {
            this.accountId = accountId;
            return this;
        }
        public String getAccountId() {
            return this.accountId;
        }

        public ImageModerationResponseBodyData setDataId(String dataId) {
            this.dataId = dataId;
            return this;
        }
        public String getDataId() {
            return this.dataId;
        }

        public ImageModerationResponseBodyData setExt(ImageModerationResponseBodyDataExt ext) {
            this.ext = ext;
            return this;
        }
        public ImageModerationResponseBodyDataExt getExt() {
            return this.ext;
        }

        public ImageModerationResponseBodyData setManualTaskId(String manualTaskId) {
            this.manualTaskId = manualTaskId;
            return this;
        }
        public String getManualTaskId() {
            return this.manualTaskId;
        }

        public ImageModerationResponseBodyData setResult(java.util.List<ImageModerationResponseBodyDataResult> result) {
            this.result = result;
            return this;
        }
        public java.util.List<ImageModerationResponseBodyDataResult> getResult() {
            return this.result;
        }

        public ImageModerationResponseBodyData setRiskLevel(String riskLevel) {
            this.riskLevel = riskLevel;
            return this;
        }
        public String getRiskLevel() {
            return this.riskLevel;
        }

    }

}
