// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.cloudapi20160714.models;

import com.aliyun.tea.*;

public class DescribeApiGroupResponseBody extends TeaModel {
    /**
     * <p>The root path of the API.</p>
     */
    @NameInMap("BasePath")
    public String basePath;

    /**
     * <p>The billing status of the API group.</p>
     * <br>
     * <p>*   **NORMAL**: The API group is normal.</p>
     * <p>*   **LOCKED**: The API group is locked due to overdue payments.</p>
     */
    @NameInMap("BillingStatus")
    public String billingStatus;

    /**
     * <p>The VPC second-level domain name.</p>
     */
    @NameInMap("ClassicVpcSubDomain")
    public String classicVpcSubDomain;

    /**
     * <p>The products on Alibaba Cloud Marketplace.</p>
     */
    @NameInMap("CloudMarketCommodity")
    public Boolean cloudMarketCommodity;

    /**
     * <p>The CloudMonitor application group.</p>
     */
    @NameInMap("CmsMonitorGroup")
    public String cmsMonitorGroup;

    /**
     * <p>The list of associated tags. Separate multiple tags with commas (,).</p>
     */
    @NameInMap("CompatibleFlags")
    public String compatibleFlags;

    /**
     * <p>The creation time (UTC) of the API group.</p>
     */
    @NameInMap("CreatedTime")
    public String createdTime;

    /**
     * <p>The custom domain name information.</p>
     */
    @NameInMap("CustomDomains")
    public DescribeApiGroupResponseBodyCustomDomains customDomains;

    /**
     * <p>The custom trace configuration.</p>
     */
    @NameInMap("CustomTraceConfig")
    public String customTraceConfig;

    /**
     * <p>The list of custom configuration items.</p>
     */
    @NameInMap("CustomerConfigs")
    public String customerConfigs;

    @NameInMap("DedicatedInstanceType")
    public String dedicatedInstanceType;

    /**
     * <p>The default domain name.</p>
     */
    @NameInMap("DefaultDomain")
    public String defaultDomain;

    /**
     * <p>The description of the API group.</p>
     */
    @NameInMap("Description")
    public String description;

    /**
     * <p>The ID of the API group. This ID is generated by the system and globally unique.</p>
     */
    @NameInMap("GroupId")
    public String groupId;

    /**
     * <p>The name of the group to which the API belongs.</p>
     */
    @NameInMap("GroupName")
    public String groupName;

    /**
     * <p>The HTTPS policy.</p>
     */
    @NameInMap("HttpsPolicy")
    public String httpsPolicy;

    /**
     * <p>The validity status of the API group. Valid values:</p>
     * <br>
     * <p>*   **NORMAL**: The API group is normal.</p>
     * <p>*   **LOCKED**: The API group is locked because it is not valid.</p>
     */
    @NameInMap("IllegalStatus")
    public String illegalStatus;

    /**
     * <p>The ID of the instance.</p>
     */
    @NameInMap("InstanceId")
    public String instanceId;

    /**
     * <p>The type of the instance.</p>
     * <br>
     * <p>*   CLASSIC_SHARED: shared instance that uses the classic network configuration</p>
     * <p>*   VPC_SHARED: shared instance that uses VPC</p>
     * <p>*   VPC_DEDICATED: dedicated instance that uses VPC</p>
     */
    @NameInMap("InstanceType")
    public String instanceType;

    /**
     * <p>The VIP list of the instance.</p>
     */
    @NameInMap("InstanceVipList")
    public String instanceVipList;

    /**
     * <p>The IPv6 status.</p>
     */
    @NameInMap("Ipv6Status")
    public String ipv6Status;

    /**
     * <p>The last modification time (UTC) of the API group.</p>
     */
    @NameInMap("ModifiedTime")
    public String modifiedTime;

    /**
     * <p>Specifies whether to pass headers.</p>
     */
    @NameInMap("PassthroughHeaders")
    public String passthroughHeaders;

    /**
     * <p>The region to which the API group belongs.</p>
     */
    @NameInMap("RegionId")
    public String regionId;

    /**
     * <p>The ID of the request.</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>The RPC mode.</p>
     */
    @NameInMap("RpcPattern")
    public String rpcPattern;

    /**
     * <p>The runtime environment information.</p>
     */
    @NameInMap("StageItems")
    public DescribeApiGroupResponseBodyStageItems stageItems;

    /**
     * <p>The status of the API group.</p>
     * <br>
     * <p>*   **NORMAL**: The API group is normal.</p>
     * <p>*   **DELETE**: The API group is deleted.</p>
     */
    @NameInMap("Status")
    public String status;

    /**
     * <p>The second-level domain name automatically assigned to the API group.</p>
     */
    @NameInMap("SubDomain")
    public String subDomain;

    /**
     * <p>The upper QPS limit of the API group. The default value is 500. You can increase the upper limit by submitting an application.</p>
     */
    @NameInMap("TrafficLimit")
    public Integer trafficLimit;

    /**
     * <p>The user log settings.</p>
     */
    @NameInMap("UserLogConfig")
    public String userLogConfig;

    /**
     * <p>The VPC domain name.</p>
     */
    @NameInMap("VpcDomain")
    public String vpcDomain;

    /**
     * <p>The VPC SLB domain name.</p>
     */
    @NameInMap("VpcSlbIntranetDomain")
    public String vpcSlbIntranetDomain;

    public static DescribeApiGroupResponseBody build(java.util.Map<String, ?> map) throws Exception {
        DescribeApiGroupResponseBody self = new DescribeApiGroupResponseBody();
        return TeaModel.build(map, self);
    }

    public DescribeApiGroupResponseBody setBasePath(String basePath) {
        this.basePath = basePath;
        return this;
    }
    public String getBasePath() {
        return this.basePath;
    }

    public DescribeApiGroupResponseBody setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus;
        return this;
    }
    public String getBillingStatus() {
        return this.billingStatus;
    }

    public DescribeApiGroupResponseBody setClassicVpcSubDomain(String classicVpcSubDomain) {
        this.classicVpcSubDomain = classicVpcSubDomain;
        return this;
    }
    public String getClassicVpcSubDomain() {
        return this.classicVpcSubDomain;
    }

    public DescribeApiGroupResponseBody setCloudMarketCommodity(Boolean cloudMarketCommodity) {
        this.cloudMarketCommodity = cloudMarketCommodity;
        return this;
    }
    public Boolean getCloudMarketCommodity() {
        return this.cloudMarketCommodity;
    }

    public DescribeApiGroupResponseBody setCmsMonitorGroup(String cmsMonitorGroup) {
        this.cmsMonitorGroup = cmsMonitorGroup;
        return this;
    }
    public String getCmsMonitorGroup() {
        return this.cmsMonitorGroup;
    }

    public DescribeApiGroupResponseBody setCompatibleFlags(String compatibleFlags) {
        this.compatibleFlags = compatibleFlags;
        return this;
    }
    public String getCompatibleFlags() {
        return this.compatibleFlags;
    }

    public DescribeApiGroupResponseBody setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
        return this;
    }
    public String getCreatedTime() {
        return this.createdTime;
    }

    public DescribeApiGroupResponseBody setCustomDomains(DescribeApiGroupResponseBodyCustomDomains customDomains) {
        this.customDomains = customDomains;
        return this;
    }
    public DescribeApiGroupResponseBodyCustomDomains getCustomDomains() {
        return this.customDomains;
    }

    public DescribeApiGroupResponseBody setCustomTraceConfig(String customTraceConfig) {
        this.customTraceConfig = customTraceConfig;
        return this;
    }
    public String getCustomTraceConfig() {
        return this.customTraceConfig;
    }

    public DescribeApiGroupResponseBody setCustomerConfigs(String customerConfigs) {
        this.customerConfigs = customerConfigs;
        return this;
    }
    public String getCustomerConfigs() {
        return this.customerConfigs;
    }

    public DescribeApiGroupResponseBody setDedicatedInstanceType(String dedicatedInstanceType) {
        this.dedicatedInstanceType = dedicatedInstanceType;
        return this;
    }
    public String getDedicatedInstanceType() {
        return this.dedicatedInstanceType;
    }

    public DescribeApiGroupResponseBody setDefaultDomain(String defaultDomain) {
        this.defaultDomain = defaultDomain;
        return this;
    }
    public String getDefaultDomain() {
        return this.defaultDomain;
    }

    public DescribeApiGroupResponseBody setDescription(String description) {
        this.description = description;
        return this;
    }
    public String getDescription() {
        return this.description;
    }

    public DescribeApiGroupResponseBody setGroupId(String groupId) {
        this.groupId = groupId;
        return this;
    }
    public String getGroupId() {
        return this.groupId;
    }

    public DescribeApiGroupResponseBody setGroupName(String groupName) {
        this.groupName = groupName;
        return this;
    }
    public String getGroupName() {
        return this.groupName;
    }

    public DescribeApiGroupResponseBody setHttpsPolicy(String httpsPolicy) {
        this.httpsPolicy = httpsPolicy;
        return this;
    }
    public String getHttpsPolicy() {
        return this.httpsPolicy;
    }

    public DescribeApiGroupResponseBody setIllegalStatus(String illegalStatus) {
        this.illegalStatus = illegalStatus;
        return this;
    }
    public String getIllegalStatus() {
        return this.illegalStatus;
    }

    public DescribeApiGroupResponseBody setInstanceId(String instanceId) {
        this.instanceId = instanceId;
        return this;
    }
    public String getInstanceId() {
        return this.instanceId;
    }

    public DescribeApiGroupResponseBody setInstanceType(String instanceType) {
        this.instanceType = instanceType;
        return this;
    }
    public String getInstanceType() {
        return this.instanceType;
    }

    public DescribeApiGroupResponseBody setInstanceVipList(String instanceVipList) {
        this.instanceVipList = instanceVipList;
        return this;
    }
    public String getInstanceVipList() {
        return this.instanceVipList;
    }

    public DescribeApiGroupResponseBody setIpv6Status(String ipv6Status) {
        this.ipv6Status = ipv6Status;
        return this;
    }
    public String getIpv6Status() {
        return this.ipv6Status;
    }

    public DescribeApiGroupResponseBody setModifiedTime(String modifiedTime) {
        this.modifiedTime = modifiedTime;
        return this;
    }
    public String getModifiedTime() {
        return this.modifiedTime;
    }

    public DescribeApiGroupResponseBody setPassthroughHeaders(String passthroughHeaders) {
        this.passthroughHeaders = passthroughHeaders;
        return this;
    }
    public String getPassthroughHeaders() {
        return this.passthroughHeaders;
    }

    public DescribeApiGroupResponseBody setRegionId(String regionId) {
        this.regionId = regionId;
        return this;
    }
    public String getRegionId() {
        return this.regionId;
    }

    public DescribeApiGroupResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public DescribeApiGroupResponseBody setRpcPattern(String rpcPattern) {
        this.rpcPattern = rpcPattern;
        return this;
    }
    public String getRpcPattern() {
        return this.rpcPattern;
    }

    public DescribeApiGroupResponseBody setStageItems(DescribeApiGroupResponseBodyStageItems stageItems) {
        this.stageItems = stageItems;
        return this;
    }
    public DescribeApiGroupResponseBodyStageItems getStageItems() {
        return this.stageItems;
    }

    public DescribeApiGroupResponseBody setStatus(String status) {
        this.status = status;
        return this;
    }
    public String getStatus() {
        return this.status;
    }

    public DescribeApiGroupResponseBody setSubDomain(String subDomain) {
        this.subDomain = subDomain;
        return this;
    }
    public String getSubDomain() {
        return this.subDomain;
    }

    public DescribeApiGroupResponseBody setTrafficLimit(Integer trafficLimit) {
        this.trafficLimit = trafficLimit;
        return this;
    }
    public Integer getTrafficLimit() {
        return this.trafficLimit;
    }

    public DescribeApiGroupResponseBody setUserLogConfig(String userLogConfig) {
        this.userLogConfig = userLogConfig;
        return this;
    }
    public String getUserLogConfig() {
        return this.userLogConfig;
    }

    public DescribeApiGroupResponseBody setVpcDomain(String vpcDomain) {
        this.vpcDomain = vpcDomain;
        return this;
    }
    public String getVpcDomain() {
        return this.vpcDomain;
    }

    public DescribeApiGroupResponseBody setVpcSlbIntranetDomain(String vpcSlbIntranetDomain) {
        this.vpcSlbIntranetDomain = vpcSlbIntranetDomain;
        return this;
    }
    public String getVpcSlbIntranetDomain() {
        return this.vpcSlbIntranetDomain;
    }

    public static class DescribeApiGroupResponseBodyCustomDomainsDomainItem extends TeaModel {
        /**
         * <p>The name of the bound runtime environment.</p>
         */
        @NameInMap("BindStageName")
        public String bindStageName;

        /**
         * <p>The unique ID of the SSL certificate, which is automatically generated by the system.</p>
         */
        @NameInMap("CertificateId")
        public String certificateId;

        /**
         * <p>The name of the SSL certificate.</p>
         */
        @NameInMap("CertificateName")
        public String certificateName;

        /**
         * <p>The type of the custom domain name.</p>
         */
        @NameInMap("CustomDomainType")
        public String customDomainType;

        /**
         * <p>The binding status of the custom domain name. Valid values:</p>
         * <br>
         * <p>*   **BINDING**: The domain name is bound.</p>
         * <p>*   **BOUND**: The domain name is not bound.</p>
         */
        @NameInMap("DomainBindingStatus")
        public String domainBindingStatus;

        /**
         * <p>The domain name resolution status. Valid values:</p>
         * <br>
         * <p>*   **RESOLVED**: The domain name has been resolved.</p>
         * <p>*   **UNRESOLVED**: The domain name has not been resolved.</p>
         */
        @NameInMap("DomainCNAMEStatus")
        public String domainCNAMEStatus;

        /**
         * <p>The validity status of the domain name. Valid values:</p>
         * <br>
         * <p>*   **NORMAL**: The domain name is valid.</p>
         * <p>*   **ABNORMAL**: The domain name is invalid. This status affects API calls and must be resolved as soon as possible.</p>
         */
        @NameInMap("DomainLegalStatus")
        public String domainLegalStatus;

        /**
         * <p>The domain name.</p>
         */
        @NameInMap("DomainName")
        public String domainName;

        /**
         * <p>The domain name-related remarks, such as the cause for a domain name exception.</p>
         */
        @NameInMap("DomainRemark")
        public String domainRemark;

        /**
         * <p>The status of the domain name that uses the WebSocket feature.</p>
         */
        @NameInMap("DomainWebSocketStatus")
        public String domainWebSocketStatus;

        /**
         * <p>Indicates whether to redirect HTTP requests to HTTPS.</p>
         */
        @NameInMap("IsHttpRedirectToHttps")
        public Boolean isHttpRedirectToHttps;

        /**
         * <p>The wildcard domain name mode.</p>
         */
        @NameInMap("WildcardDomainPatterns")
        public String wildcardDomainPatterns;

        @NameInMap("WssEnable")
        public String wssEnable;

        public static DescribeApiGroupResponseBodyCustomDomainsDomainItem build(java.util.Map<String, ?> map) throws Exception {
            DescribeApiGroupResponseBodyCustomDomainsDomainItem self = new DescribeApiGroupResponseBodyCustomDomainsDomainItem();
            return TeaModel.build(map, self);
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setBindStageName(String bindStageName) {
            this.bindStageName = bindStageName;
            return this;
        }
        public String getBindStageName() {
            return this.bindStageName;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setCertificateId(String certificateId) {
            this.certificateId = certificateId;
            return this;
        }
        public String getCertificateId() {
            return this.certificateId;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setCertificateName(String certificateName) {
            this.certificateName = certificateName;
            return this;
        }
        public String getCertificateName() {
            return this.certificateName;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setCustomDomainType(String customDomainType) {
            this.customDomainType = customDomainType;
            return this;
        }
        public String getCustomDomainType() {
            return this.customDomainType;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainBindingStatus(String domainBindingStatus) {
            this.domainBindingStatus = domainBindingStatus;
            return this;
        }
        public String getDomainBindingStatus() {
            return this.domainBindingStatus;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainCNAMEStatus(String domainCNAMEStatus) {
            this.domainCNAMEStatus = domainCNAMEStatus;
            return this;
        }
        public String getDomainCNAMEStatus() {
            return this.domainCNAMEStatus;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainLegalStatus(String domainLegalStatus) {
            this.domainLegalStatus = domainLegalStatus;
            return this;
        }
        public String getDomainLegalStatus() {
            return this.domainLegalStatus;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainName(String domainName) {
            this.domainName = domainName;
            return this;
        }
        public String getDomainName() {
            return this.domainName;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainRemark(String domainRemark) {
            this.domainRemark = domainRemark;
            return this;
        }
        public String getDomainRemark() {
            return this.domainRemark;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainWebSocketStatus(String domainWebSocketStatus) {
            this.domainWebSocketStatus = domainWebSocketStatus;
            return this;
        }
        public String getDomainWebSocketStatus() {
            return this.domainWebSocketStatus;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setIsHttpRedirectToHttps(Boolean isHttpRedirectToHttps) {
            this.isHttpRedirectToHttps = isHttpRedirectToHttps;
            return this;
        }
        public Boolean getIsHttpRedirectToHttps() {
            return this.isHttpRedirectToHttps;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setWildcardDomainPatterns(String wildcardDomainPatterns) {
            this.wildcardDomainPatterns = wildcardDomainPatterns;
            return this;
        }
        public String getWildcardDomainPatterns() {
            return this.wildcardDomainPatterns;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setWssEnable(String wssEnable) {
            this.wssEnable = wssEnable;
            return this;
        }
        public String getWssEnable() {
            return this.wssEnable;
        }

    }

    public static class DescribeApiGroupResponseBodyCustomDomains extends TeaModel {
        @NameInMap("DomainItem")
        public java.util.List<DescribeApiGroupResponseBodyCustomDomainsDomainItem> domainItem;

        public static DescribeApiGroupResponseBodyCustomDomains build(java.util.Map<String, ?> map) throws Exception {
            DescribeApiGroupResponseBodyCustomDomains self = new DescribeApiGroupResponseBodyCustomDomains();
            return TeaModel.build(map, self);
        }

        public DescribeApiGroupResponseBodyCustomDomains setDomainItem(java.util.List<DescribeApiGroupResponseBodyCustomDomainsDomainItem> domainItem) {
            this.domainItem = domainItem;
            return this;
        }
        public java.util.List<DescribeApiGroupResponseBodyCustomDomainsDomainItem> getDomainItem() {
            return this.domainItem;
        }

    }

    public static class DescribeApiGroupResponseBodyStageItemsStageInfo extends TeaModel {
        /**
         * <p>The description of the runtime environment.</p>
         */
        @NameInMap("Description")
        public String description;

        /**
         * <p>The ID of the runtime environment.</p>
         */
        @NameInMap("StageId")
        public String stageId;

        /**
         * <p>The name of the runtime environment.</p>
         */
        @NameInMap("StageName")
        public String stageName;

        public static DescribeApiGroupResponseBodyStageItemsStageInfo build(java.util.Map<String, ?> map) throws Exception {
            DescribeApiGroupResponseBodyStageItemsStageInfo self = new DescribeApiGroupResponseBodyStageItemsStageInfo();
            return TeaModel.build(map, self);
        }

        public DescribeApiGroupResponseBodyStageItemsStageInfo setDescription(String description) {
            this.description = description;
            return this;
        }
        public String getDescription() {
            return this.description;
        }

        public DescribeApiGroupResponseBodyStageItemsStageInfo setStageId(String stageId) {
            this.stageId = stageId;
            return this;
        }
        public String getStageId() {
            return this.stageId;
        }

        public DescribeApiGroupResponseBodyStageItemsStageInfo setStageName(String stageName) {
            this.stageName = stageName;
            return this;
        }
        public String getStageName() {
            return this.stageName;
        }

    }

    public static class DescribeApiGroupResponseBodyStageItems extends TeaModel {
        @NameInMap("StageInfo")
        public java.util.List<DescribeApiGroupResponseBodyStageItemsStageInfo> stageInfo;

        public static DescribeApiGroupResponseBodyStageItems build(java.util.Map<String, ?> map) throws Exception {
            DescribeApiGroupResponseBodyStageItems self = new DescribeApiGroupResponseBodyStageItems();
            return TeaModel.build(map, self);
        }

        public DescribeApiGroupResponseBodyStageItems setStageInfo(java.util.List<DescribeApiGroupResponseBodyStageItemsStageInfo> stageInfo) {
            this.stageInfo = stageInfo;
            return this;
        }
        public java.util.List<DescribeApiGroupResponseBodyStageItemsStageInfo> getStageInfo() {
            return this.stageInfo;
        }

    }

}
