// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.cloudapi20160714.models;

import com.aliyun.tea.*;

public class DescribeApiGroupResponseBody extends TeaModel {
    /**
     * <p>The root path of the API.</p>
     * 
     * <strong>example:</strong>
     * <p>/qqq</p>
     */
    @NameInMap("BasePath")
    public String basePath;

    /**
     * <p>The billing status of the API group.</p>
     * <ul>
     * <li><strong>NORMAL</strong>: The API group is normal.</li>
     * <li><strong>LOCKED</strong>: The API group is locked due to overdue payments.</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>NORMAL</p>
     */
    @NameInMap("BillingStatus")
    public String billingStatus;

    /**
     * <p>The products on Alibaba Cloud Marketplace.</p>
     * 
     * <strong>example:</strong>
     * <p>false</p>
     */
    @NameInMap("CloudMarketCommodity")
    public Boolean cloudMarketCommodity;

    /**
     * <p>The CloudMonitor application group.</p>
     * 
     * <strong>example:</strong>
     * <p>217008423</p>
     */
    @NameInMap("CmsMonitorGroup")
    public String cmsMonitorGroup;

    /**
     * <p>The list of associated tags. Separate multiple tags with commas (,).</p>
     * 
     * <strong>example:</strong>
     * <p>depart:dep1</p>
     */
    @NameInMap("CompatibleFlags")
    public String compatibleFlags;

    /**
     * <p>The creation time (UTC) of the API group.</p>
     * 
     * <strong>example:</strong>
     * <p>2016-08-01T06:53:02Z</p>
     */
    @NameInMap("CreatedTime")
    public String createdTime;

    /**
     * <p>The custom appcode configuration.</p>
     * 
     * <strong>example:</strong>
     * <p>{&quot;location&quot;:&quot;HEADER&quot;,&quot;name&quot;:&quot;myAppCodeHeader&quot;}</p>
     */
    @NameInMap("CustomAppCodeConfig")
    public String customAppCodeConfig;

    /**
     * <p>The details about the custom domain name.</p>
     */
    @NameInMap("CustomDomains")
    public DescribeApiGroupResponseBodyCustomDomains customDomains;

    /**
     * <p>The custom trace configuration.</p>
     * 
     * <strong>example:</strong>
     * <p>{\&quot;parameterLocation\&quot;:\&quot;HEADER\&quot;,\&quot;parameterName\&quot;:\&quot;traceId\&quot;}</p>
     */
    @NameInMap("CustomTraceConfig")
    public String customTraceConfig;

    /**
     * <p>The list of custom configuration items.</p>
     * 
     * <strong>example:</strong>
     * <p>removeResponseServerHeader</p>
     */
    @NameInMap("CustomerConfigs")
    public String customerConfigs;

    /**
     * <p>The type of exclusive instance where the group is located</p>
     * <ul>
     * <li>VPC fusion type exclusive instance: vpc_connect</li>
     * <li>Traditional type exclusive instance: normal</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>normal</p>
     */
    @NameInMap("DedicatedInstanceType")
    public String dedicatedInstanceType;

    /**
     * <p>The default domain name.</p>
     * 
     * <strong>example:</strong>
     * <p>mkt.api.gaore.com</p>
     */
    @NameInMap("DefaultDomain")
    public String defaultDomain;

    /**
     * <p>The description of the API group.</p>
     * 
     * <strong>example:</strong>
     * <p>New weather informations.</p>
     */
    @NameInMap("Description")
    public String description;

    /**
     * <p>Indicates whether access over the public second-level domain name is enabled. Valid values:</p>
     * <ul>
     * <li>true</li>
     * <li>false</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>false</p>
     */
    @NameInMap("DisableInnerDomain")
    public Boolean disableInnerDomain;

    /**
     * <p>The ID of the API group. This ID is generated by the system and globally unique.</p>
     * 
     * <strong>example:</strong>
     * <p>523e8dc7bbe04613b5b1d726c2a7889d</p>
     */
    @NameInMap("GroupId")
    public String groupId;

    /**
     * <p>The name of the group to which the API belongs.</p>
     * 
     * <strong>example:</strong>
     * <p>NewWeather</p>
     */
    @NameInMap("GroupName")
    public String groupName;

    /**
     * <p>The HTTPS policy.</p>
     * 
     * <strong>example:</strong>
     * <p>HTTPS2_TLS1_0</p>
     */
    @NameInMap("HttpsPolicy")
    public String httpsPolicy;

    /**
     * <p>The validity status of the API group. Valid values:</p>
     * <ul>
     * <li><strong>NORMAL</strong>: The API group is normal.</li>
     * <li><strong>LOCKED</strong>: The API group is locked because it is not valid.</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>NORMAL</p>
     */
    @NameInMap("IllegalStatus")
    public String illegalStatus;

    /**
     * <p>The ID of the instance.</p>
     * 
     * <strong>example:</strong>
     * <p>apigateway-cn-v6419k43xxxxx</p>
     */
    @NameInMap("InstanceId")
    public String instanceId;

    /**
     * <p>The type of the instance.</p>
     * <ul>
     * <li>CLASSIC_SHARED: shared instance that uses the classic network configuration</li>
     * <li>VPC_SHARED: shared instance that uses VPC</li>
     * <li>VPC_DEDICATED: dedicated instance that uses VPC</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>VPC_SHARED</p>
     */
    @NameInMap("InstanceType")
    public String instanceType;

    /**
     * <p>The IPv6 status.</p>
     * 
     * <strong>example:</strong>
     * <p>UNBIND</p>
     */
    @NameInMap("Ipv6Status")
    public String ipv6Status;

    /**
     * <p>The reason for the failure of the group migration instance task. When the value of the MigrationStatus parameter is Failed, it is not empty.</p>
     * 
     * <strong>example:</strong>
     * <p>The current instance conflicts with the target instance.</p>
     */
    @NameInMap("MigrationError")
    public String migrationError;

    /**
     * <p>Group migration instance task status</p>
     * <ul>
     * <li>Running</li>
     * <li>Success</li>
     * <li>Failed</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>Fail</p>
     */
    @NameInMap("MigrationStatus")
    public String migrationStatus;

    /**
     * <p>The last modification time (UTC) of the API group.</p>
     * 
     * <strong>example:</strong>
     * <p>2016-08-01T06:54:32Z</p>
     */
    @NameInMap("ModifiedTime")
    public String modifiedTime;

    /**
     * <p>Specifies whether to pass headers.</p>
     * 
     * <strong>example:</strong>
     * <p>eagleeye-rpcid,x-b3-traceid</p>
     */
    @NameInMap("PassthroughHeaders")
    public String passthroughHeaders;

    /**
     * <p>The region to which the API group belongs.</p>
     * 
     * <strong>example:</strong>
     * <p>cn-hangzhou</p>
     */
    @NameInMap("RegionId")
    public String regionId;

    /**
     * <p>The ID of the request.</p>
     * 
     * <strong>example:</strong>
     * <p>03442A3D-3B7D-434C-8A95-A5FEB989B519</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>The runtime environment information.</p>
     */
    @NameInMap("StageItems")
    public DescribeApiGroupResponseBodyStageItems stageItems;

    /**
     * <p>The status of the API group.</p>
     * <ul>
     * <li><strong>NORMAL</strong>: The API group is normal.</li>
     * <li><strong>DELETE</strong>: The API group is deleted.</li>
     * </ul>
     * 
     * <strong>example:</strong>
     * <p>NORMAL</p>
     */
    @NameInMap("Status")
    public String status;

    /**
     * <p>The second-level domain name automatically assigned to the API group.</p>
     * 
     * <strong>example:</strong>
     * <p>27d50c0f2e54b359919923d908bb015-cn-hangzhou.alicloudapi.com</p>
     */
    @NameInMap("SubDomain")
    public String subDomain;

    /**
     * <p>The upper QPS limit of the API group. The default value is 500. You can increase the upper limit by submitting an application.</p>
     * 
     * <strong>example:</strong>
     * <p>500</p>
     */
    @NameInMap("TrafficLimit")
    public Integer trafficLimit;

    /**
     * <p>The user log settings.</p>
     * 
     * <strong>example:</strong>
     * <p>{\&quot;requestBody\&quot;:true,\&quot;responseBody\&quot;:true,\&quot;queryString\&quot;:\&quot;test\&quot;,\&quot;requestHeaders\&quot;:\&quot;test\&quot;,\&quot;responseHeaders\&quot;:\&quot;test\&quot;,\&quot;jwtClaims\&quot;:\&quot;test\&quot;}</p>
     */
    @NameInMap("UserLogConfig")
    public String userLogConfig;

    /**
     * <p>The VPC domain name.</p>
     * 
     * <strong>example:</strong>
     * <p>e4<em><em><strong>7151954</strong></em>acbd9f7</em>***1058a-ap-southeast-1-vpc.alicloudapi.com</p>
     */
    @NameInMap("VpcDomain")
    public String vpcDomain;

    /**
     * <p>The VPC SLB domain name.</p>
     * 
     * <strong>example:</strong>
     * <p>257e9d450e924d00b976b0ecfb7184c2-cn-beijing-intranet.alicloudapi.com</p>
     */
    @NameInMap("VpcSlbIntranetDomain")
    public String vpcSlbIntranetDomain;

    public static DescribeApiGroupResponseBody build(java.util.Map<String, ?> map) throws Exception {
        DescribeApiGroupResponseBody self = new DescribeApiGroupResponseBody();
        return TeaModel.build(map, self);
    }

    public DescribeApiGroupResponseBody setBasePath(String basePath) {
        this.basePath = basePath;
        return this;
    }
    public String getBasePath() {
        return this.basePath;
    }

    public DescribeApiGroupResponseBody setBillingStatus(String billingStatus) {
        this.billingStatus = billingStatus;
        return this;
    }
    public String getBillingStatus() {
        return this.billingStatus;
    }

    public DescribeApiGroupResponseBody setCloudMarketCommodity(Boolean cloudMarketCommodity) {
        this.cloudMarketCommodity = cloudMarketCommodity;
        return this;
    }
    public Boolean getCloudMarketCommodity() {
        return this.cloudMarketCommodity;
    }

    public DescribeApiGroupResponseBody setCmsMonitorGroup(String cmsMonitorGroup) {
        this.cmsMonitorGroup = cmsMonitorGroup;
        return this;
    }
    public String getCmsMonitorGroup() {
        return this.cmsMonitorGroup;
    }

    public DescribeApiGroupResponseBody setCompatibleFlags(String compatibleFlags) {
        this.compatibleFlags = compatibleFlags;
        return this;
    }
    public String getCompatibleFlags() {
        return this.compatibleFlags;
    }

    public DescribeApiGroupResponseBody setCreatedTime(String createdTime) {
        this.createdTime = createdTime;
        return this;
    }
    public String getCreatedTime() {
        return this.createdTime;
    }

    public DescribeApiGroupResponseBody setCustomAppCodeConfig(String customAppCodeConfig) {
        this.customAppCodeConfig = customAppCodeConfig;
        return this;
    }
    public String getCustomAppCodeConfig() {
        return this.customAppCodeConfig;
    }

    public DescribeApiGroupResponseBody setCustomDomains(DescribeApiGroupResponseBodyCustomDomains customDomains) {
        this.customDomains = customDomains;
        return this;
    }
    public DescribeApiGroupResponseBodyCustomDomains getCustomDomains() {
        return this.customDomains;
    }

    public DescribeApiGroupResponseBody setCustomTraceConfig(String customTraceConfig) {
        this.customTraceConfig = customTraceConfig;
        return this;
    }
    public String getCustomTraceConfig() {
        return this.customTraceConfig;
    }

    public DescribeApiGroupResponseBody setCustomerConfigs(String customerConfigs) {
        this.customerConfigs = customerConfigs;
        return this;
    }
    public String getCustomerConfigs() {
        return this.customerConfigs;
    }

    public DescribeApiGroupResponseBody setDedicatedInstanceType(String dedicatedInstanceType) {
        this.dedicatedInstanceType = dedicatedInstanceType;
        return this;
    }
    public String getDedicatedInstanceType() {
        return this.dedicatedInstanceType;
    }

    public DescribeApiGroupResponseBody setDefaultDomain(String defaultDomain) {
        this.defaultDomain = defaultDomain;
        return this;
    }
    public String getDefaultDomain() {
        return this.defaultDomain;
    }

    public DescribeApiGroupResponseBody setDescription(String description) {
        this.description = description;
        return this;
    }
    public String getDescription() {
        return this.description;
    }

    public DescribeApiGroupResponseBody setDisableInnerDomain(Boolean disableInnerDomain) {
        this.disableInnerDomain = disableInnerDomain;
        return this;
    }
    public Boolean getDisableInnerDomain() {
        return this.disableInnerDomain;
    }

    public DescribeApiGroupResponseBody setGroupId(String groupId) {
        this.groupId = groupId;
        return this;
    }
    public String getGroupId() {
        return this.groupId;
    }

    public DescribeApiGroupResponseBody setGroupName(String groupName) {
        this.groupName = groupName;
        return this;
    }
    public String getGroupName() {
        return this.groupName;
    }

    public DescribeApiGroupResponseBody setHttpsPolicy(String httpsPolicy) {
        this.httpsPolicy = httpsPolicy;
        return this;
    }
    public String getHttpsPolicy() {
        return this.httpsPolicy;
    }

    public DescribeApiGroupResponseBody setIllegalStatus(String illegalStatus) {
        this.illegalStatus = illegalStatus;
        return this;
    }
    public String getIllegalStatus() {
        return this.illegalStatus;
    }

    public DescribeApiGroupResponseBody setInstanceId(String instanceId) {
        this.instanceId = instanceId;
        return this;
    }
    public String getInstanceId() {
        return this.instanceId;
    }

    public DescribeApiGroupResponseBody setInstanceType(String instanceType) {
        this.instanceType = instanceType;
        return this;
    }
    public String getInstanceType() {
        return this.instanceType;
    }

    public DescribeApiGroupResponseBody setIpv6Status(String ipv6Status) {
        this.ipv6Status = ipv6Status;
        return this;
    }
    public String getIpv6Status() {
        return this.ipv6Status;
    }

    public DescribeApiGroupResponseBody setMigrationError(String migrationError) {
        this.migrationError = migrationError;
        return this;
    }
    public String getMigrationError() {
        return this.migrationError;
    }

    public DescribeApiGroupResponseBody setMigrationStatus(String migrationStatus) {
        this.migrationStatus = migrationStatus;
        return this;
    }
    public String getMigrationStatus() {
        return this.migrationStatus;
    }

    public DescribeApiGroupResponseBody setModifiedTime(String modifiedTime) {
        this.modifiedTime = modifiedTime;
        return this;
    }
    public String getModifiedTime() {
        return this.modifiedTime;
    }

    public DescribeApiGroupResponseBody setPassthroughHeaders(String passthroughHeaders) {
        this.passthroughHeaders = passthroughHeaders;
        return this;
    }
    public String getPassthroughHeaders() {
        return this.passthroughHeaders;
    }

    public DescribeApiGroupResponseBody setRegionId(String regionId) {
        this.regionId = regionId;
        return this;
    }
    public String getRegionId() {
        return this.regionId;
    }

    public DescribeApiGroupResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public DescribeApiGroupResponseBody setStageItems(DescribeApiGroupResponseBodyStageItems stageItems) {
        this.stageItems = stageItems;
        return this;
    }
    public DescribeApiGroupResponseBodyStageItems getStageItems() {
        return this.stageItems;
    }

    public DescribeApiGroupResponseBody setStatus(String status) {
        this.status = status;
        return this;
    }
    public String getStatus() {
        return this.status;
    }

    public DescribeApiGroupResponseBody setSubDomain(String subDomain) {
        this.subDomain = subDomain;
        return this;
    }
    public String getSubDomain() {
        return this.subDomain;
    }

    public DescribeApiGroupResponseBody setTrafficLimit(Integer trafficLimit) {
        this.trafficLimit = trafficLimit;
        return this;
    }
    public Integer getTrafficLimit() {
        return this.trafficLimit;
    }

    public DescribeApiGroupResponseBody setUserLogConfig(String userLogConfig) {
        this.userLogConfig = userLogConfig;
        return this;
    }
    public String getUserLogConfig() {
        return this.userLogConfig;
    }

    public DescribeApiGroupResponseBody setVpcDomain(String vpcDomain) {
        this.vpcDomain = vpcDomain;
        return this;
    }
    public String getVpcDomain() {
        return this.vpcDomain;
    }

    public DescribeApiGroupResponseBody setVpcSlbIntranetDomain(String vpcSlbIntranetDomain) {
        this.vpcSlbIntranetDomain = vpcSlbIntranetDomain;
        return this;
    }
    public String getVpcSlbIntranetDomain() {
        return this.vpcSlbIntranetDomain;
    }

    public static class DescribeApiGroupResponseBodyCustomDomainsDomainItem extends TeaModel {
        /**
         * <p>The alias of the associated environment.</p>
         * 
         * <strong>example:</strong>
         * <p>TEST1</p>
         */
        @NameInMap("BindStageAlias")
        public String bindStageAlias;

        /**
         * <p>The environment in which the associated API group runs.</p>
         * 
         * <strong>example:</strong>
         * <p>TEST</p>
         */
        @NameInMap("BindStageName")
        public String bindStageName;

        /**
         * <p>The SSL certificate ID, which is automatically generated by the system.</p>
         * 
         * <strong>example:</strong>
         * <p>6EF60BEC-0242-43AF-BB20-270359FB54A7</p>
         */
        @NameInMap("CertificateId")
        public String certificateId;

        /**
         * <p>The name of the SSL certificate.</p>
         * 
         * <strong>example:</strong>
         * <p>myCertificate</p>
         */
        @NameInMap("CertificateName")
        public String certificateName;

        /**
         * <p>The time when the certificate expires.</p>
         * 
         * <strong>example:</strong>
         * <p>2635123476000</p>
         */
        @NameInMap("CertificateValidEnd")
        public Long certificateValidEnd;

        /**
         * <p>The time when the certificate takes effect.</p>
         * 
         * <strong>example:</strong>
         * <p>1689043476000</p>
         */
        @NameInMap("CertificateValidStart")
        public Long certificateValidStart;

        @NameInMap("ClientCertSDnPassThrough")
        public Boolean clientCertSDnPassThrough;

        /**
         * <p>The type of the custom domain name.</p>
         * 
         * <strong>example:</strong>
         * <p>intranet</p>
         */
        @NameInMap("CustomDomainType")
        public String customDomainType;

        /**
         * <p>The binding status of the custom domain name. Valid values:</p>
         * <ul>
         * <li><strong>BINDING</strong>: The domain name is bound.</li>
         * <li><strong>BOUND</strong>: The domain name is not bound.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>BINDING</p>
         */
        @NameInMap("DomainBindingStatus")
        public String domainBindingStatus;

        /**
         * <p>The domain name resolution status. Valid values:</p>
         * <ul>
         * <li><strong>RESOLVED</strong></li>
         * <li><strong>UNRESOLVED</strong></li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>RESOLVED</p>
         */
        @NameInMap("DomainCNAMEStatus")
        public String domainCNAMEStatus;

        /**
         * <p>The validity status of the domain name. Valid values:</p>
         * <ul>
         * <li><strong>NORMAL</strong>: The domain name is valid.</li>
         * <li><strong>ABNORMAL</strong>: The domain name is invalid. This status affects API calls and needs to be rectified as soon as possible.</li>
         * </ul>
         * 
         * <strong>example:</strong>
         * <p>ABNORMAL</p>
         */
        @NameInMap("DomainLegalStatus")
        public String domainLegalStatus;

        /**
         * <p>The domain name.</p>
         * 
         * <strong>example:</strong>
         * <p>api.demo.com</p>
         */
        @NameInMap("DomainName")
        public String domainName;

        /**
         * <p>Remarks about the domain name, such as the cause of an exception.</p>
         * 
         * <strong>example:</strong>
         * <p>Indicates that the domain name does not have an ICP filing.</p>
         */
        @NameInMap("DomainRemark")
        public String domainRemark;

        /**
         * <p>The status of the domain that uses the WebSocket feature.</p>
         * 
         * <strong>example:</strong>
         * <p>CLOSE</p>
         */
        @NameInMap("DomainWebSocketStatus")
        public String domainWebSocketStatus;

        /**
         * <p>Indicates whether to redirect HTTP requests to HTTPS.</p>
         * 
         * <strong>example:</strong>
         * <p>false</p>
         */
        @NameInMap("IsHttpRedirectToHttps")
        public Boolean isHttpRedirectToHttps;

        @NameInMap("SslOcspCacheEnable")
        public Boolean sslOcspCacheEnable;

        @NameInMap("SslOcspEnable")
        public Boolean sslOcspEnable;

        @NameInMap("SslVerifyDepth")
        public Integer sslVerifyDepth;

        /**
         * <p>The wildcard domain name mode.</p>
         * 
         * <strong>example:</strong>
         * <p>[\&quot;{test}.test.com\&quot;]</p>
         */
        @NameInMap("WildcardDomainPatterns")
        public String wildcardDomainPatterns;

        public static DescribeApiGroupResponseBodyCustomDomainsDomainItem build(java.util.Map<String, ?> map) throws Exception {
            DescribeApiGroupResponseBodyCustomDomainsDomainItem self = new DescribeApiGroupResponseBodyCustomDomainsDomainItem();
            return TeaModel.build(map, self);
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setBindStageAlias(String bindStageAlias) {
            this.bindStageAlias = bindStageAlias;
            return this;
        }
        public String getBindStageAlias() {
            return this.bindStageAlias;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setBindStageName(String bindStageName) {
            this.bindStageName = bindStageName;
            return this;
        }
        public String getBindStageName() {
            return this.bindStageName;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setCertificateId(String certificateId) {
            this.certificateId = certificateId;
            return this;
        }
        public String getCertificateId() {
            return this.certificateId;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setCertificateName(String certificateName) {
            this.certificateName = certificateName;
            return this;
        }
        public String getCertificateName() {
            return this.certificateName;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setCertificateValidEnd(Long certificateValidEnd) {
            this.certificateValidEnd = certificateValidEnd;
            return this;
        }
        public Long getCertificateValidEnd() {
            return this.certificateValidEnd;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setCertificateValidStart(Long certificateValidStart) {
            this.certificateValidStart = certificateValidStart;
            return this;
        }
        public Long getCertificateValidStart() {
            return this.certificateValidStart;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setClientCertSDnPassThrough(Boolean clientCertSDnPassThrough) {
            this.clientCertSDnPassThrough = clientCertSDnPassThrough;
            return this;
        }
        public Boolean getClientCertSDnPassThrough() {
            return this.clientCertSDnPassThrough;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setCustomDomainType(String customDomainType) {
            this.customDomainType = customDomainType;
            return this;
        }
        public String getCustomDomainType() {
            return this.customDomainType;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainBindingStatus(String domainBindingStatus) {
            this.domainBindingStatus = domainBindingStatus;
            return this;
        }
        public String getDomainBindingStatus() {
            return this.domainBindingStatus;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainCNAMEStatus(String domainCNAMEStatus) {
            this.domainCNAMEStatus = domainCNAMEStatus;
            return this;
        }
        public String getDomainCNAMEStatus() {
            return this.domainCNAMEStatus;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainLegalStatus(String domainLegalStatus) {
            this.domainLegalStatus = domainLegalStatus;
            return this;
        }
        public String getDomainLegalStatus() {
            return this.domainLegalStatus;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainName(String domainName) {
            this.domainName = domainName;
            return this;
        }
        public String getDomainName() {
            return this.domainName;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainRemark(String domainRemark) {
            this.domainRemark = domainRemark;
            return this;
        }
        public String getDomainRemark() {
            return this.domainRemark;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setDomainWebSocketStatus(String domainWebSocketStatus) {
            this.domainWebSocketStatus = domainWebSocketStatus;
            return this;
        }
        public String getDomainWebSocketStatus() {
            return this.domainWebSocketStatus;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setIsHttpRedirectToHttps(Boolean isHttpRedirectToHttps) {
            this.isHttpRedirectToHttps = isHttpRedirectToHttps;
            return this;
        }
        public Boolean getIsHttpRedirectToHttps() {
            return this.isHttpRedirectToHttps;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setSslOcspCacheEnable(Boolean sslOcspCacheEnable) {
            this.sslOcspCacheEnable = sslOcspCacheEnable;
            return this;
        }
        public Boolean getSslOcspCacheEnable() {
            return this.sslOcspCacheEnable;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setSslOcspEnable(Boolean sslOcspEnable) {
            this.sslOcspEnable = sslOcspEnable;
            return this;
        }
        public Boolean getSslOcspEnable() {
            return this.sslOcspEnable;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setSslVerifyDepth(Integer sslVerifyDepth) {
            this.sslVerifyDepth = sslVerifyDepth;
            return this;
        }
        public Integer getSslVerifyDepth() {
            return this.sslVerifyDepth;
        }

        public DescribeApiGroupResponseBodyCustomDomainsDomainItem setWildcardDomainPatterns(String wildcardDomainPatterns) {
            this.wildcardDomainPatterns = wildcardDomainPatterns;
            return this;
        }
        public String getWildcardDomainPatterns() {
            return this.wildcardDomainPatterns;
        }

    }

    public static class DescribeApiGroupResponseBodyCustomDomains extends TeaModel {
        @NameInMap("DomainItem")
        public java.util.List<DescribeApiGroupResponseBodyCustomDomainsDomainItem> domainItem;

        public static DescribeApiGroupResponseBodyCustomDomains build(java.util.Map<String, ?> map) throws Exception {
            DescribeApiGroupResponseBodyCustomDomains self = new DescribeApiGroupResponseBodyCustomDomains();
            return TeaModel.build(map, self);
        }

        public DescribeApiGroupResponseBodyCustomDomains setDomainItem(java.util.List<DescribeApiGroupResponseBodyCustomDomainsDomainItem> domainItem) {
            this.domainItem = domainItem;
            return this;
        }
        public java.util.List<DescribeApiGroupResponseBodyCustomDomainsDomainItem> getDomainItem() {
            return this.domainItem;
        }

    }

    public static class DescribeApiGroupResponseBodyStageItemsStageInfo extends TeaModel {
        /**
         * <p>The environment description.</p>
         * 
         * <strong>example:</strong>
         * <p>MYTEST</p>
         */
        @NameInMap("Description")
        public String description;

        /**
         * <p>The environment ID.</p>
         * 
         * <strong>example:</strong>
         * <p>123e8dc7bbe01613b5b1d726c2a7888e</p>
         */
        @NameInMap("StageId")
        public String stageId;

        /**
         * <p>The environment name.</p>
         * 
         * <strong>example:</strong>
         * <p>TEST</p>
         */
        @NameInMap("StageName")
        public String stageName;

        public static DescribeApiGroupResponseBodyStageItemsStageInfo build(java.util.Map<String, ?> map) throws Exception {
            DescribeApiGroupResponseBodyStageItemsStageInfo self = new DescribeApiGroupResponseBodyStageItemsStageInfo();
            return TeaModel.build(map, self);
        }

        public DescribeApiGroupResponseBodyStageItemsStageInfo setDescription(String description) {
            this.description = description;
            return this;
        }
        public String getDescription() {
            return this.description;
        }

        public DescribeApiGroupResponseBodyStageItemsStageInfo setStageId(String stageId) {
            this.stageId = stageId;
            return this;
        }
        public String getStageId() {
            return this.stageId;
        }

        public DescribeApiGroupResponseBodyStageItemsStageInfo setStageName(String stageName) {
            this.stageName = stageName;
            return this;
        }
        public String getStageName() {
            return this.stageName;
        }

    }

    public static class DescribeApiGroupResponseBodyStageItems extends TeaModel {
        @NameInMap("StageInfo")
        public java.util.List<DescribeApiGroupResponseBodyStageItemsStageInfo> stageInfo;

        public static DescribeApiGroupResponseBodyStageItems build(java.util.Map<String, ?> map) throws Exception {
            DescribeApiGroupResponseBodyStageItems self = new DescribeApiGroupResponseBodyStageItems();
            return TeaModel.build(map, self);
        }

        public DescribeApiGroupResponseBodyStageItems setStageInfo(java.util.List<DescribeApiGroupResponseBodyStageItemsStageInfo> stageInfo) {
            this.stageInfo = stageInfo;
            return this;
        }
        public java.util.List<DescribeApiGroupResponseBodyStageItemsStageInfo> getStageInfo() {
            return this.stageInfo;
        }

    }

}
