// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.cloudapi20160714.models;

import com.aliyun.tea.*;

public class ModifyApiGroupResponseBody extends TeaModel {
    /**
     * <p>The root path of the API.</p>
     */
    @NameInMap("BasePath")
    public String basePath;

    /**
     * <p>The description of the API group.</p>
     */
    @NameInMap("Description")
    public String description;

    /**
     * <p>The ID of the API group. This ID is generated by the system and globally unique.</p>
     */
    @NameInMap("GroupId")
    public String groupId;

    /**
     * <p>The name of the group to which an API belongs.</p>
     */
    @NameInMap("GroupName")
    public String groupName;

    /**
     * <p>The ID of the request.</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>The second-level domain name automatically assigned to the API group.</p>
     */
    @NameInMap("SubDomain")
    public String subDomain;

    public static ModifyApiGroupResponseBody build(java.util.Map<String, ?> map) throws Exception {
        ModifyApiGroupResponseBody self = new ModifyApiGroupResponseBody();
        return TeaModel.build(map, self);
    }

    public ModifyApiGroupResponseBody setBasePath(String basePath) {
        this.basePath = basePath;
        return this;
    }
    public String getBasePath() {
        return this.basePath;
    }

    public ModifyApiGroupResponseBody setDescription(String description) {
        this.description = description;
        return this;
    }
    public String getDescription() {
        return this.description;
    }

    public ModifyApiGroupResponseBody setGroupId(String groupId) {
        this.groupId = groupId;
        return this;
    }
    public String getGroupId() {
        return this.groupId;
    }

    public ModifyApiGroupResponseBody setGroupName(String groupName) {
        this.groupName = groupName;
        return this;
    }
    public String getGroupName() {
        return this.groupName;
    }

    public ModifyApiGroupResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public ModifyApiGroupResponseBody setSubDomain(String subDomain) {
        this.subDomain = subDomain;
        return this;
    }
    public String getSubDomain() {
        return this.subDomain;
    }

}
