// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.cloudapi20160714.models;

import com.aliyun.tea.*;

public class SdkGenerateByGroupRequest extends TeaModel {
    /**
     * <p>The ID of the API group. This ID is generated by the system and is globally unique.</p>
     */
    @NameInMap("GroupId")
    public String groupId;

    /**
     * <p>The language in which the result is returned. Valid values: **zh-cn** (Chinese) and **en-us** (English). The default value is zh-cn.</p>
     */
    @NameInMap("Language")
    public String language;

    @NameInMap("SecurityToken")
    public String securityToken;

    public static SdkGenerateByGroupRequest build(java.util.Map<String, ?> map) throws Exception {
        SdkGenerateByGroupRequest self = new SdkGenerateByGroupRequest();
        return TeaModel.build(map, self);
    }

    public SdkGenerateByGroupRequest setGroupId(String groupId) {
        this.groupId = groupId;
        return this;
    }
    public String getGroupId() {
        return this.groupId;
    }

    public SdkGenerateByGroupRequest setLanguage(String language) {
        this.language = language;
        return this;
    }
    public String getLanguage() {
        return this.language;
    }

    public SdkGenerateByGroupRequest setSecurityToken(String securityToken) {
        this.securityToken = securityToken;
        return this;
    }
    public String getSecurityToken() {
        return this.securityToken;
    }

}
