// This file is auto-generated, don't edit it. Thanks.
package com.aliyun.cloudapi20160714.models;

import com.aliyun.tea.*;

public class SetDomainResponseBody extends TeaModel {
    /**
     * <p>The binding status of the custom domain name. Valid values:</p>
     * <br>
     * <p>*   **BINDING**: The domain name has been bound.</p>
     * <p>*   **BOUND**: The domain name has not been bound.</p>
     */
    @NameInMap("DomainBindingStatus")
    public String domainBindingStatus;

    /**
     * <p>The validity status of the domain name. Valid values:</p>
     * <br>
     * <p>*   **NORMAL**: The domain name is valid.</p>
     * <p>*   **ABNORMAL**: The domain name is invalid. This status affects API calls and must be resolved as soon as possible.</p>
     */
    @NameInMap("DomainLegalStatus")
    public String domainLegalStatus;

    /**
     * <p>The custom domain name.</p>
     */
    @NameInMap("DomainName")
    public String domainName;

    /**
     * <p>The remarks on the domain name, such as the cause of an exception.</p>
     */
    @NameInMap("DomainRemark")
    public String domainRemark;

    /**
     * <p>The status of the domain name that uses the WebSocket feature.</p>
     */
    @NameInMap("DomainWebSocketStatus")
    public String domainWebSocketStatus;

    /**
     * <p>The ID of the API group. This ID is generated by the system and globally unique.</p>
     */
    @NameInMap("GroupId")
    public String groupId;

    /**
     * <p>The ID of the request.</p>
     */
    @NameInMap("RequestId")
    public String requestId;

    /**
     * <p>The second-level domain name assigned to the API group. This domain name is used to test API calls.</p>
     */
    @NameInMap("SubDomain")
    public String subDomain;

    public static SetDomainResponseBody build(java.util.Map<String, ?> map) throws Exception {
        SetDomainResponseBody self = new SetDomainResponseBody();
        return TeaModel.build(map, self);
    }

    public SetDomainResponseBody setDomainBindingStatus(String domainBindingStatus) {
        this.domainBindingStatus = domainBindingStatus;
        return this;
    }
    public String getDomainBindingStatus() {
        return this.domainBindingStatus;
    }

    public SetDomainResponseBody setDomainLegalStatus(String domainLegalStatus) {
        this.domainLegalStatus = domainLegalStatus;
        return this;
    }
    public String getDomainLegalStatus() {
        return this.domainLegalStatus;
    }

    public SetDomainResponseBody setDomainName(String domainName) {
        this.domainName = domainName;
        return this;
    }
    public String getDomainName() {
        return this.domainName;
    }

    public SetDomainResponseBody setDomainRemark(String domainRemark) {
        this.domainRemark = domainRemark;
        return this;
    }
    public String getDomainRemark() {
        return this.domainRemark;
    }

    public SetDomainResponseBody setDomainWebSocketStatus(String domainWebSocketStatus) {
        this.domainWebSocketStatus = domainWebSocketStatus;
        return this;
    }
    public String getDomainWebSocketStatus() {
        return this.domainWebSocketStatus;
    }

    public SetDomainResponseBody setGroupId(String groupId) {
        this.groupId = groupId;
        return this;
    }
    public String getGroupId() {
        return this.groupId;
    }

    public SetDomainResponseBody setRequestId(String requestId) {
        this.requestId = requestId;
        return this;
    }
    public String getRequestId() {
        return this.requestId;
    }

    public SetDomainResponseBody setSubDomain(String subDomain) {
        this.subDomain = subDomain;
        return this;
    }
    public String getSubDomain() {
        return this.subDomain;
    }

}
